import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, 'dist');
const indexPath = join(distDir, 'index.html');

if (!existsSync(indexPath)) {
  console.error('ERROR: dist/index.html no encontrado. Ejecuta vite build primero.');
  process.exit(1);
}

const baseHtml = readFileSync(indexPath, 'utf-8');

const routes = [
  // Páginas principales
  { path: 'servicios', title: 'Servicios de Ingeniería Hidráulica — BIC Bernal Ingeniería | Manizales', desc: 'Hidrosanitario, CI NSR-10, HEC-RAS 2D, acueducto, alcantarillado, gestión del riesgo, regalías MGA-Web. BIC — Manizales, Eje Cafetero, Colombia.', url: 'https://ingenieriabernal.co/servicios' },
  { path: 'proyectos', title: 'Proyectos Ejecutados — BIC Bernal Ingeniería | Caldas y Colombia', desc: 'Portafolio verificado: Palacio de Justicia La Dorada, Makarí Mall Dosquebradas, EPANET Manizales, torrencialidad Eje Cafetero. BIC — más de 10 años de experiencia.', url: 'https://ingenieriabernal.co/proyectos' },
  { path: 'equipo', title: 'Equipo Consultor — BIC Bernal Ingeniería Consultores | Manizales', desc: 'Rogerio Bernal Ríos, Ing. Civil Esp. Hidráulica UNAL, COPNIA 17202-313228. Equipo multidisciplinario: hidráulica, geotecnia, arquitectura, ambiental.', url: 'https://ingenieriabernal.co/equipo' },
  { path: 'blog', title: 'Blog Ingeniería Hidráulica Colombia — Artículos Técnicos BIC', desc: 'Artículos técnicos: HEC-RAS 2D, NSR-10 sistemas CI, costos obras 2026, regalías MGA-Web, normativa hídrica colombiana. Por Rogerio Bernal Ríos.', url: 'https://ingenieriabernal.co/blog' },
  { path: 'contacto', title: 'Contacto — BIC Bernal Ingeniería Consultores | Manizales, Colombia', desc: 'Contáctenos para proyectos de ingeniería hidráulica, hidrosanitaria y gestión del riesgo. Manizales, Eje Cafetero, Colombia.', url: 'https://ingenieriabernal.co/contacto' },
  { path: 'sobre-mi', title: 'Sobre Mí — Rogerio Bernal Ríos | BIC Bernal Ingeniería Consultores', desc: 'Rogerio Bernal Ríos, Ingeniero Civil UNAL Manizales, Especialista en Hidráulica. Director de BIC Bernal Ingeniería Consultores. COPNIA 17202-313228. Más de 10 años de experiencia.', url: 'https://ingenieriabernal.co/sobre-mi' },
  { path: 'credenciales', title: 'Credenciales y Certificaciones | BIC Bernal Ingeniería Consultores', desc: 'Credenciales de Rogerio Bernal Ríos: Ing. Civil UNAL, Especialista Hidráulica, COPNIA 17202-313228, TOEFL 98/120. Experiencia internacional en Ecuador y México.', url: 'https://ingenieriabernal.co/credenciales' },
  { path: 'cobertura-nacional', title: 'Cobertura Nacional — Ingeniería Hidráulica Colombia | BIC', desc: 'BIC Bernal Ingeniería Consultores presta servicios en todo Colombia: Eje Cafetero, Bogotá, Medellín, Cali, Barranquilla, Bucaramanga y regiones del Pacífico, Caribe y Llanos.', url: 'https://ingenieriabernal.co/cobertura-nacional' },

  // Páginas de servicio nacional (con componente React propio)
  { path: 'bocatomas-colombia', title: 'Diseño de Bocatomas en Colombia — Ingeniería Hidráulica Especializada | BIC', desc: 'BIC diseña bocatomas laterales, frontales, de fondo y sumergidas en Colombia. Análisis hidrológico, modelación HEC-RAS, memoria de cálculo COPNIA y permisos CAR para acueductos, riego e industria. Cotización en 24 horas.', url: 'https://ingenieriabernal.co/bocatomas-colombia' },
  { path: 'diseno-canal-riego-colombia', title: 'Diseño de Canales de Riego en Colombia — Ingeniería Hidráulica | BIC', desc: 'BIC diseña canales de riego, conducción y drenaje en Colombia. Canales revestidos, en tierra y entubados con cálculo hidráulico, obras de arte y memoria COPNIA. Distritos de riego, municipios y agroindustria. Cotización en 24 horas.', url: 'https://ingenieriabernal.co/diseno-canal-riego-colombia' },
  { path: 'encauzamiento-rios-colombia', title: 'Encauzamiento de Ríos y Quebradas en Colombia — Ingeniería Fluvial | BIC', desc: 'BIC diseña obras de encauzamiento fluvial en Colombia: rectificación de cauces, muros laterales, espigones y revestimientos. Modelación HEC-RAS 2D, permiso CAR. Para municipios con ríos en zona urbana, vías y predios ribereños.', url: 'https://ingenieriabernal.co/encauzamiento-rios-colombia' },
  { path: 'estudios-torrencialidad-colombia', title: 'Estudios de Torrencialidad en Colombia — Amenaza Torrencial y Flujos de Escombros | BIC', desc: 'BIC realiza estudios de torrencialidad en Colombia: mapas de amenaza torrencial, modelación de flujos de escombros (FLO-2D, RAMMS), delimitación de retiros y planes de gestión del riesgo. Decreto 1807/2014, Ley 1523/2012. Cobertura nacional.', url: 'https://ingenieriabernal.co/estudios-torrencialidad-colombia' },
  { path: 'ingenieria-hidraulica-manizales', title: 'Ingeniería Hidráulica en Manizales y el Eje Cafetero | BIC', desc: 'BIC es la firma de ingeniería hidráulica con base en Manizales. Bocatomas, canales, encauzamientos, estudios hidrológicos y gestión del riesgo en Caldas, Risaralda y Quindío. Ante CORPOCALDAS, CARDER y CRQ. Cotización en 24 horas.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-manizales' },
  { path: 'plan-parcial-colombia', title: 'Formulación de Planes Parciales en Colombia — Consultoría Técnica | BIC', desc: 'BIC formula y tramita planes parciales en Colombia. Suelo de expansión urbana, cargas y beneficios, coordinación POT y curaduría. Para propietarios de terrenos, promotores inmobiliarios y fiduciarias. Cotización sin costo.', url: 'https://ingenieriabernal.co/plan-parcial-colombia' },
  { path: 'ingenieria-hidraulica-colombia', title: 'Ingeniería Hidráulica Colombia | BIC Bernal Ingeniería Consultores', desc: 'Consultoría especializada en ingeniería hidráulica para proyectos en Colombia. Modelación HEC-RAS, diseño hidrosanitario, acueductos, riesgo hídrico. COPNIA 17202-313228. Atención nacional.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-colombia' },
  { path: 'gestion-riesgo-hidrico', title: 'Gestión del Riesgo Hídrico Colombia | BIC Bernal Ingeniería', desc: 'Estudios de amenaza y riesgo por inundación y avenidas torrenciales en Colombia. Decreto 1807/2014, Ley 1523/2012, PMGR municipales, mapas de amenaza hídrica. COPNIA vigente.', url: 'https://ingenieriabernal.co/gestion-riesgo-hidrico' },
  { path: 'obras-hidraulicas-colombia', title: 'Obras Hidráulicas Colombia — Diseño y Construcción | BIC', desc: 'Diseño y consultoría de obras hidráulicas en Colombia. Acueductos, alcantarillados, PTAP. Ing. Bernal COPNIA. Caldas y Eje Cafetero.', url: 'https://ingenieriabernal.co/obras-hidraulicas-colombia' },
  { path: 'urbanizacion-colombia', title: 'Ingeniería para Urbanizaciones en Colombia | BIC Bernal Ingeniería', desc: 'BIC diseña las redes hidrosanitarias, estudios de riesgo hídrico y sistemas contra incendios para urbanizaciones en Colombia. Conjuntos residenciales, parques industriales, centros comerciales. Resolución 0330/2017, Decreto 1807/2014. Cotice en 24 horas.', url: 'https://ingenieriabernal.co/urbanizacion-colombia' },
  { path: 'licencia-de-urbanismo', title: 'Licencia de Urbanismo Colombia: Estudios Técnicos Requeridos | BIC', desc: 'BIC prepara todos los estudios técnicos para tramitar su licencia de urbanismo en Colombia: hidrosanitario, riesgo hídrico Decreto 1807, acueducto y alcantarillado. Urbanizaciones residenciales, comerciales e industriales. Propuesta en 24 horas.', url: 'https://ingenieriabernal.co/licencia-de-urbanismo' },
  { path: 'construir-cerca-rio-quebrada-colombia', title: 'Construir Cerca a un Río o Quebrada en Colombia — Permisos, Estudios y Ronda Hídrica | BIC', desc: 'Si quiere construir cerca a un río, quebrada o canal en Colombia, necesita estudio de ronda hídrica, zonificación de amenaza y permiso de ocupación de cauce. BIC elabora todos los estudios requeridos por la CAR y la curaduría. Manizales, Eje Cafetero y todo Colombia.', url: 'https://ingenieriabernal.co/construir-cerca-rio-quebrada-colombia' },
  { path: 'ingenieria-proyectos-urbanisticos-colombia', title: 'Ingeniería para Proyectos Urbanísticos en Colombia — Hidráulica, Hidrosanitario y Estudios | BIC', desc: 'BIC diseña las redes hidrosanitarias, el sistema de drenaje pluvial y los estudios de amenaza hídrica para proyectos urbanísticos en Colombia. Memorias de cálculo firmadas, planos constructivos y acompañamiento hasta la licencia. Manizales, Eje Cafetero y todo el país.', url: 'https://ingenieriabernal.co/ingenieria-proyectos-urbanisticos-colombia' },
  { path: 'obras-civiles-hidraulicas-colombia', title: 'Obras Civiles Hidráulicas en Colombia — Diseño, Modelación e Interventoría | BIC', desc: 'BIC diseña y hace interventoría de obras civiles hidráulicas en Colombia: encauzamientos, diques, gaviones, disipadores de energía, box culvert, alcantarillas y estructuras de control de crecientes. HEC-RAS 2D, planos AutoCAD, firma COPNIA. Eje Cafetero y todo el país.', url: 'https://ingenieriabernal.co/obras-civiles-hidraulicas-colombia' },
  { path: 'estudios-hidrologicos-vias-colombia', title: 'Estudios Hidrológicos para Vías en Colombia — Drenaje Vial, INVIAS y Proyectos 4G | BIC', desc: 'BIC elabora estudios hidrológicos e hidráulicos para vías en Colombia: diseño de drenaje transversal y longitudinal, alcantarillas, box culvert y obras de protección. Metodología INVIAS, HEC-HMS, HEC-RAS. Memorias de cálculo firmadas COPNIA para proyectos nacionales, departamentales y municipales.', url: 'https://ingenieriabernal.co/estudios-hidrologicos-vias-colombia' },
  { path: 'memorias-hidrosanitarias-colombia', title: 'Memorias Hidrosanitarias Colombia — NSR-10 RAS | BIC', desc: 'Memorias de cálculo hidrosanitarias para licencias de construcción. NSR-10, RAS 2017. Manizales y Eje Cafetero. Ing. Bernal COPNIA. Cotiza ya.', url: 'https://ingenieriabernal.co/memorias-hidrosanitarias-colombia' },
  { path: 'me-pidieron-estudios-en-la-car', title: 'Me Pidieron Estudios en la CAR Colombia — ¿Qué Necesito y Cómo Obtenerlos? | BIC', desc: 'Si la CAR le pidió estudios para una concesión de aguas, permiso de vertimiento, ocupación de cauce o plan de manejo ambiental, BIC los elabora. Eje Cafetero (CORPOCALDAS, CARDER, CRQ) y todo Colombia. Propuesta técnica en 24 horas.', url: 'https://ingenieriabernal.co/me-pidieron-estudios-en-la-car' },
  { path: 'tengo-un-lote-colombia', title: 'Tengo un Lote y Quiero Construir — ¿Qué Estudios de Ingeniería Necesito? | BIC', desc: 'Si tiene un lote en Colombia y quiere construir, BIC le dice exactamente qué estudios técnicos necesita: ronda hídrica, amenaza sísmica, estudio de suelos, hidrosanitario y más. Orientación gratuita en 24 horas. Eje Cafetero y todo Colombia.', url: 'https://ingenieriabernal.co/tengo-un-lote-colombia' },
  { path: 'gestion-riesgo-taludes-colombia', title: 'Gestión de Riesgo en Taludes Colombia — Estabilidad, Deslizamientos y Amenaza | BIC', desc: 'BIC elabora estudios de gestión de riesgo en taludes para Colombia: análisis de estabilidad, zonificación de amenaza por movimientos en masa, Plan de Emergencias y diseño de obras de estabilización. Manizales, Eje Cafetero, zonas andinas y todo el país.', url: 'https://ingenieriabernal.co/gestion-riesgo-taludes-colombia' },
  { path: 'ingenieria-hidraulica-colombia-desde-manizales', title: 'Ingeniería Hidráulica en Colombia desde Manizales — BIC Bernal Ingeniería | Nacional', desc: 'BIC Bernal Ingeniería Consultores opera desde Manizales con ingeniería hidráulica para toda Colombia. Hidrología, HEC-RAS 2D, bocatomas, encauzamientos, PTAR y estudios ambientales para proyectos en Bogotá, Medellín, Cali, Barranquilla y todo el país. Graduados UN Manizales, 15+ años de experiencia.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-colombia-desde-manizales' },
  { path: 'modelacion-hidraulica-colombia', title: 'Modelación Hidráulica en Colombia — HEC-RAS 1D y 2D | BIC Ingeniería', desc: 'BIC realiza modelación hidráulica con HEC-RAS 1D y 2D para estudios de inundación, licencias de urbanismo y Decreto 1807 en Colombia. Resultados verificables. Cotice en 24 horas.', url: 'https://ingenieriabernal.co/modelacion-hidraulica-colombia' },
  { path: 'diseno-ptar-colombia', title: 'Diseño PTAR Colombia — Plantas Tratamiento Aguas | BIC', desc: 'Diseño de PTAR y sistemas de tratamiento de aguas residuales. RAS 2017, NSR-10. Caldas y Eje Cafetero. Ing. Bernal COPNIA. Cotiza sin costo.', url: 'https://ingenieriabernal.co/diseno-ptar-colombia' },
  { path: 'concesion-aguas-colombia', title: 'Concesión de Aguas en Colombia — Trámite ante CAR | BIC Ingeniería', desc: 'BIC elabora los estudios técnicos para tramitar concesiones de aguas superficiales y subterráneas ante las CAR en Colombia. Decreto 1076/2015. Aforos, hidrología y oferta hídrica. Cotice en 24 horas.', url: 'https://ingenieriabernal.co/concesion-aguas-colombia' },
  { path: 'diseno-ptap-colombia', title: 'Diseño de PTAP en Colombia — Plantas de Tratamiento Agua Potable | BIC', desc: 'BIC diseña plantas de tratamiento de agua potable (PTAP) para municipios y acueductos en Colombia conforme al RAS 2017 y Resolución 0330. Memoria COPNIA, trámite CAR. Cotice en 24 horas.', url: 'https://ingenieriabernal.co/diseno-ptap-colombia' },
  { path: 'diseno-alcantarillado-colombia', title: 'Diseño de Alcantarillado Colombia | Redes Sanitarias y Pluviales | BIC', desc: 'Diseño de redes de alcantarillado sanitario y pluvial en Colombia. Cumplimiento RAS 2017, NTC 1339. Memoria de cálculo, planos AutoCAD, EPANET. Ing. Rogerio Bernal — Manizales.', url: 'https://ingenieriabernal.co/diseno-alcantarillado-colombia' },
  { path: 'pomca-colombia', title: 'POMCA Colombia — Plan de Ordenación y Manejo de Cuencas | BIC', desc: 'Formulación y ajuste de POMCA en Colombia. Fase diagnóstico, prospectiva, zonificación ambiental. Decreto 1076/2015, Ley 388/1997. Consultoría especializada desde Manizales.', url: 'https://ingenieriabernal.co/pomca-colombia' },

  // Servicios específicos (sub-páginas)
  { path: 'servicios/estudio-inundabilidad-manizales', title: 'Estudio de Inundabilidad Manizales | BIC Bernal Ingeniería', desc: 'Estudio de inundabilidad en Manizales con modelación HEC-RAS 2D. Requerido por Corpocaldas, POT Manizales y POMCA Chinchiná. Manchas de inundación Decreto 1807/2014. COPNIA vigente. Cotice hoy.', url: 'https://ingenieriabernal.co/servicios/estudio-inundabilidad-manizales' },
  { path: 'servicios/estudios-hidrologicos', title: 'Estudios Hidrológicos Colombia | BIC Bernal Ingeniería', desc: 'Estudios hidrológicos con HEC-HMS para municipios, constructoras y entidades en Colombia. Curvas IDF, caudales de diseño, períodos de retorno. Especialista UNAL. COPNIA 17202-313228. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/estudios-hidrologicos' },
  { path: 'servicios/modelacion-hec-ras', title: 'Modelación HEC-RAS 2D Colombia | BIC Bernal Ingeniería', desc: 'Modelación hidráulica HEC-RAS 1D y 2D para municipios y constructoras en Colombia. Manchas de inundación, amenaza hídrica Decreto 1807/2014. Especialista UNAL. COPNIA 17202-313228. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/modelacion-hec-ras' },
  { path: 'servicios/acueducto-alcantarillado', title: 'Diseño Acueducto y Alcantarillado Colombia | BIC Bernal', desc: 'Diseño de acueductos y alcantarillados conforme al RAS 2017 y Resolución 0330/2017 para municipios y constructoras. EPANET, SWMM, PTAP, PTAR. COPNIA 17202-313228. Cotice su proyecto hoy.', url: 'https://ingenieriabernal.co/servicios/acueducto-alcantarillado' },
  { path: 'servicios/redes-hidrosanitarias', title: 'Redes Hidrosanitarias NSR-10 Colombia | BIC Bernal Ingeniería', desc: 'Diseño de redes hidrosanitarias para edificios residenciales, comerciales e industriales en Colombia. Agua fría, agua caliente, aguas residuales y lluvias. NSR-10, RAS 2017. COPNIA vigente.', url: 'https://ingenieriabernal.co/servicios/redes-hidrosanitarias' },
  { path: 'servicios/sistemas-contra-incendio', title: 'Sistemas Contra Incendio NSR-10 Colombia | BIC Bernal', desc: 'Diseño de sistemas contra incendio NSR-10 Títulos J y K para edificios, centros comerciales e industrias en Colombia. Rociadores NFPA, hidrantes NTC 2301. COPNIA 17202-313228. Manizales.', url: 'https://ingenieriabernal.co/servicios/sistemas-contra-incendio' },
  { path: 'servicios/interventoria', title: 'Interventoría Obras Hidráulicas Colombia — COPNIA | BIC', desc: 'Interventoría técnica de obras de acueducto, PTAP y redes hidrosanitarias. Ing. Rogerio Bernal, COPNIA Caldas. Consulta gratis hoy.', url: 'https://ingenieriabernal.co/servicios/interventoria' },
  { path: 'servicios/regalias-mga', title: 'Formulación Regalías MGA-Web Colombia | BIC Bernal Ingeniería', desc: 'Formulación de proyectos de inversión en MGA-Web para el SGR. Agua potable, saneamiento básico y gestión del riesgo. Contrato verificable Alcaldía Puerto Boyacá 621/2021. COPNIA vigente.', url: 'https://ingenieriabernal.co/servicios/regalias-mga' },
  { path: 'servicios/geotecnia', title: 'Estudios Geotécnicos Colombia | BIC Bernal Ingeniería Consultores', desc: 'Estudios geotécnicos y de suelos para constructoras y municipios en Colombia. Capacidad portante, estabilidad de taludes, NSR-10 Título H. Especialista UNAL. COPNIA 17202-313228. Manizales.', url: 'https://ingenieriabernal.co/servicios/geotecnia' },
  { path: 'servicios/ambiental', title: 'Estudios Ambientales e IRCA Colombia | BIC Bernal Ingeniería', desc: 'Estudios ambientales, cálculo IRCA, permisos de vertimientos y concesiones de agua ante CAR en Colombia. Especialista UNAL en Ingeniería Hidráulica y Ambiental. COPNIA 17202-313228.', url: 'https://ingenieriabernal.co/servicios/ambiental' },
  { path: 'servicios/diseno-acueductos', title: 'Diseño Acueductos Colombia 2026 — Ing. Bernal | BIC', desc: 'Diseño de sistemas de acueducto con RAS 2017 en Caldas y Eje Cafetero. COPNIA 17202-313228. Entrega en 4 semanas. Solicita tu cotización.', url: 'https://ingenieriabernal.co/servicios/diseno-acueductos' },
  { path: 'servicios/contra-incendios-nsr10', title: 'Sistemas Contra Incendios NSR-10 Títulos J y K Colombia | BIC', desc: 'Diseño de sistemas contra incendios NSR-10 Títulos J y K para edificios, centros comerciales e industria en Colombia. Rociadores NFPA 13, hidrantes NFPA 14, bombas NFPA 20. COPNIA 17202-313228.', url: 'https://ingenieriabernal.co/servicios/contra-incendios-nsr10' },
  { path: 'servicios/bogota', title: 'Consultoría hidráulica e hidrológica en Bogotá | BIC Ingeniería', desc: 'Consultoría hidráulica e hidrológica en Bogotá y Cundinamarca: POT, estudios de inundación río Bogotá, diseño de acueductos, planes parciales y riesgo hídrico. BIC · COPNIA · UNAL.', url: 'https://ingenieriabernal.co/servicios/bogota' },
  { path: 'servicios/medellin', title: 'Ingeniero hidráulico en Medellín — Ingeniería Bernal', desc: 'Ingeniero hidráulico en Medellín y Antioquia: estudios hidrológicos, modelación HEC-RAS, riesgo hídrico cerros y quebradas, diseño acueductos, planes parciales AMVA. BIC · COPNIA · UNAL.', url: 'https://ingenieriabernal.co/servicios/medellin' },
  { path: 'servicios/cali', title: 'Estudios hidrológicos e hidráulicos en Cali | BIC Ingeniería', desc: 'Estudios hidrológicos e hidráulicos en Cali y Valle del Cauca: modelación río Cauca y río Cali, riesgo hídrico POT, diseño acueductos y alcantarillado, CVC. BIC · COPNIA · UNAL.', url: 'https://ingenieriabernal.co/servicios/cali' },
  { path: 'servicios/ibague', title: 'Consultoría hidráulica en Ibagué — Ingeniería Bernal', desc: 'Consultoría hidráulica en Ibagué y Tolima: estudios hidrológicos río Combeima y Coello, riesgo hídrico POT, diseño acueductos, alcantarillado y trámites CORTOLIMA. BIC · COPNIA · UNAL.', url: 'https://ingenieriabernal.co/servicios/ibague' },
  { path: 'servicios/bucaramanga', title: 'Estudios hidráulicos en Bucaramanga | BIC Ingeniería', desc: 'Estudios hidráulicos en Bucaramanga y Santander: cañones, taludes, gestión del riesgo CDMB, diseño acueductos, planes parciales Área Metropolitana. BIC · COPNIA · UNAL.', url: 'https://ingenieriabernal.co/servicios/bucaramanga' },

  // Páginas regionales SEO
  { path: 'regional/manizales', title: 'Ingeniería Hidráulica Manizales | BIC Bernal Ingeniería Consultores', desc: 'BIC tiene su sede en Manizales. Estudios hidrológicos, diseño de acueductos, alcantarillados y modelación HEC-RAS para alcaldías, constructoras y ESP en Caldas y Eje Cafetero.', url: 'https://ingenieriabernal.co/regional/manizales' },
  { path: 'regional/pereira', title: 'Ingeniería Hidráulica Pereira | BIC Bernal Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica y sanitaria en Pereira y Risaralda. Diseño de acueductos, redes contra incendio y modelaciones HEC-RAS para sector público y privado.', url: 'https://ingenieriabernal.co/regional/pereira' },
  { path: 'regional/armenia', title: 'Ingeniería Hidráulica Armenia | BIC Bernal Ingeniería Consultores', desc: 'Consultoría hidráulica en Armenia y Quindío. Estudios hidráulicos, formulación de proyectos de regalías (MGA-Web) y diseño de redes hidrosanitarias con cumplimiento RAS 2017.', url: 'https://ingenieriabernal.co/regional/armenia' },
  { path: 'regional/eje-cafetero', title: 'Consultoría Hidráulica Eje Cafetero | BIC Bernal Ingeniería Consultores', desc: 'BIC opera en todo el Eje Cafetero — Caldas, Risaralda y Quindío. Consultoría integral en ingeniería hidráulica, sanitaria y ambiental para infraestructura pública y privada.', url: 'https://ingenieriabernal.co/regional/eje-cafetero' },

  // Landing pages locales — Manizales
  { path: 'estudio-de-inundabilidad-manizales', title: 'Estudio de Inundabilidad en Manizales | BIC Ingeniería', desc: 'Estudios de inundabilidad en Manizales con modelación HEC-RAS 2D. Requerido por Corpocaldas, POMCA y POT. Solicite cotización: +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-inundabilidad-manizales' },
  { path: 'estudio-de-suelos-manizales', title: 'Estudio de Suelos en Manizales | BIC Ingeniería', desc: 'Realizamos estudios de suelos en Manizales según NSR-10. Informe geotécnico completo para licencia de construcción. Solicite cotización: +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-manizales' },
  { path: 'licencia-de-construccion-manizales', title: 'Licencia de Construcción Manizales: Documentos Técnicos | BIC', desc: 'BIC prepara todos los estudios técnicos para su licencia de construcción en Manizales: suelos, estructural y planos. +57 302 477 8910', url: 'https://ingenieriabernal.co/licencia-de-construccion-manizales' },
  { path: 'estudio-de-suelos-pereira', title: 'Estudio de Suelos en Pereira | BIC Ingeniería', desc: 'Realizamos estudios de suelos en Pereira según NSR-10. Informe geotécnico completo para licencia de construcción en Risaralda. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-pereira' },
  { path: 'diseno-hidraulico-manizales', title: 'Diseño Hidráulico en Manizales | BIC Ingeniería', desc: 'Diseño hidráulico en Manizales: redes de acueducto, alcantarillado, canales y estructuras. BIC cumple RAS 2017 y normativa vigente. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-manizales' },
  { path: 'modelacion-hidraulica-manizales', title: 'Modelación Hidráulica en Manizales | BIC Ingeniería', desc: 'Modelación hidráulica 1D y 2D en Manizales con HEC-RAS. Análisis de inundaciones, socavación y diseño de obras. +57 302 477 8910', url: 'https://ingenieriabernal.co/modelacion-hidraulica-manizales' },
  { path: 'estudio-hidrologico-manizales', title: 'Estudio Hidrológico en Manizales | BIC Ingeniería', desc: 'Estudios hidrológicos en Manizales: caudales de diseño, curvas IDF, períodos de retorno. Cumplimiento RAS 2017 y EIA. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-hidrologico-manizales' },
  { path: 'interventoria-hidraulica-manizales', title: 'Interventoría Hidráulica en Manizales | BIC Ingeniería', desc: 'Interventoría técnica de obras hidráulicas en Manizales y Caldas. Acueductos, alcantarillados, canales. RAS 2017. +57 302 477 8910', url: 'https://ingenieriabernal.co/interventoria-hidraulica-manizales' },
  { path: 'diseno-hidraulico-pereira', title: 'Diseño Hidráulico en Pereira | BIC Ingeniería', desc: 'Diseño hidráulico en Pereira: redes de acueducto, alcantarillado, canales. Cumplimos RAS 2017 y normativa CARDER. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-pereira' },
  { path: 'estudio-de-inundabilidad-pereira', title: 'Estudio de Inundabilidad en Pereira | BIC Ingeniería', desc: 'Estudios de inundabilidad en Pereira con HEC-RAS 2D. Requerido por CARDER, POT Pereira y licencias de construcción. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-inundabilidad-pereira' },
  { path: 'licencia-de-construccion-pereira', title: 'Licencia de Construcción Pereira: Documentos Técnicos | BIC', desc: 'BIC prepara estudios técnicos para licencia de construcción en Pereira: suelos, estructural, planos. Curadurías de Pereira. +57 302 477 8910', url: 'https://ingenieriabernal.co/licencia-de-construccion-pereira' },
  { path: 'estudio-de-suelos-eje-cafetero', title: 'Estudio de Suelos Eje Cafetero | BIC Ingeniería', desc: 'Estudios de suelos en el Eje Cafetero: Manizales, Pereira y Armenia. Suelos volcánicos y cenizas del Quindío. NSR-10. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-eje-cafetero' },
  { path: 'consultoria-ingenieria-civil-manizales', title: 'Consultoría Ingeniería Civil Manizales | BIC', desc: 'Consultoría integral de ingeniería civil en Manizales: estudios técnicos, diseño, interventoría y gestión de proyectos. +57 302 477 8910', url: 'https://ingenieriabernal.co/consultoria-ingenieria-civil-manizales' },
  { path: 'gestion-riesgo-hidrico-manizales', title: 'Gestión del Riesgo Hídrico Manizales | BIC Ingeniería', desc: 'Gestión del riesgo por inundaciones y avenidas torrenciales en Manizales y Caldas. Planes de contingencia y mitigación. +57 302 477 8910', url: 'https://ingenieriabernal.co/gestion-riesgo-hidrico-manizales' },
  { path: 'diseno-hidraulico-eje-cafetero', title: 'Diseño Hidráulico Eje Cafetero | BIC Ingeniería', desc: 'Diseño hidráulico en Caldas, Risaralda y Quindío. Redes de acueducto, alcantarillado y estructuras. BIC cubre todo el Eje Cafetero. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-eje-cafetero' },
  { path: 'topografia-manizales', title: 'Topografía en Manizales | BIC Ingeniería', desc: 'Levantamientos topográficos en Manizales para diseño hidráulico, licencias de construcción y estudios de suelos. +57 302 477 8910', url: 'https://ingenieriabernal.co/topografia-manizales' },
  { path: 'ingeniero-hidraulico-manizales', title: 'Ingeniero Hidráulico Manizales — Rogerio Bernal COPNIA', desc: 'Servicios de ingeniería hidráulica en Manizales y Caldas. Diseño acueductos, PTAR, hidrosanitarias. COPNIA 17202-313228. Consulta sin costo.', url: 'https://ingenieriabernal.co/ingeniero-hidraulico-manizales' },

  // Páginas de ciudad — CityPage
  { path: 'manizales', title: 'Ingeniería Hidráulica Manizales — BIC Bernal Ingeniería | Ciudad Base', desc: 'Ciudad base de BIC. Proyectos activos en drenaje urbano, hidrosanitarios, sistemas CI y gestión del riesgo para planes parciales y POT en Manizales, Caldas.', url: 'https://ingenieriabernal.co/manizales' },
  { path: 'eje-cafetero', title: 'Ingeniería Hidráulica Eje Cafetero — BIC Bernal Ingeniería', desc: 'BIC ejecutó diseño hidrosanitario y CI del Makarí Mall en Dosquebradas. Estudios riesgo hídrico, sistemas CI NSR-10, acueducto y alcantarillado en Pereira, Armenia y Dosquebradas.', url: 'https://ingenieriabernal.co/eje-cafetero' },
  { path: 'palestina-aerocafe', title: 'Ingeniería Hidráulica Palestina — Aerocafé | BIC Bernal', desc: 'Sede del Aeropuerto Internacional del Café. Drenaje pluvial aeroportuario, estudios riesgo hídrico Decreto 1807, diseño hidrosanitario industrial. Inversión activa $828.000 millones, Palestina Caldas.', url: 'https://ingenieriabernal.co/palestina-aerocafe' },
  { path: 'viterbo-occidente-caldas', title: 'Ingeniería Hidráulica Viterbo y Occidente de Caldas — BIC', desc: 'Zona de clientela directa de BIC. EOT componente hídrico, acueducto y alcantarillado municipal, proyectos regalías. Anserma, Belalcázar, San José, Risaralda municipio, Caldas.', url: 'https://ingenieriabernal.co/viterbo-occidente-caldas' },
  { path: 'alto-occidente-caldas', title: 'Ingeniería Hidráulica Alto Occidente de Caldas — BIC', desc: 'Corredor minero Riosucio, Supía, Marmato, Filadelfia, La Merced. Centro Desarrollo Minero Marmato $21.000 millones. Estudios geotécnicos, hidráulicos y riesgo. Formulación regalías SGR.', url: 'https://ingenieriabernal.co/alto-occidente-caldas' },
  { path: 'magdalena-medio', title: 'Ingeniería Hidráulica Magdalena Medio — BIC Bernal', desc: 'La Dorada, Honda, Puerto Boyacá, Barrancabermeja. BIC ejecutó Palacio de Justicia La Dorada. Estudios inundación río Magdalena, sistemas CI, formulación proyectos regalías MGA-Web.', url: 'https://ingenieriabernal.co/magdalena-medio' },
  { path: 'norte-tolima', title: 'Ingeniería Hidráulica Norte del Tolima — BIC Bernal', desc: 'Líbano, Fresno, Mariquita, Herveo, Honda. Zona sin competencia SEO. Acueducto y alcantarillado rural, estudios riesgo hídrico, gestión POT. BIC Bernal Ingeniería.', url: 'https://ingenieriabernal.co/norte-tolima' },
  { path: 'cerritos-norte-valle', title: 'Ingeniería Hidráulica Cerritos y Norte del Valle — BIC', desc: '22 planes parciales activos en Cerritos y Norte del Valle. Estudios riesgo hídrico obligatorio Decreto 1807/2014. Drenaje pluvial industrial, sistemas CI NSR-10. Cartago, Valle del Cauca.', url: 'https://ingenieriabernal.co/cerritos-norte-valle' },
  { path: 'rionegro-oriente-antioquia', title: 'Ingeniería Hidráulica Rionegro y Oriente Antioquia — BIC', desc: 'Parques industriales, centros logísticos, urbanizaciones en expansión. Corredor Aeropuerto José María Córdova. Estudios riesgo hídrico, diseño hidrosanitario, sistemas CI. BIC Bernal.', url: 'https://ingenieriabernal.co/rionegro-oriente-antioquia' },
  { path: 'sabana-occidente', title: 'Ingeniería Hidráulica Sabana Occidente — BIC Bernal', desc: 'Mosquera, Facatativá, Madrid, Funza, Bojacá. Corredor industrial Cundinamarca. Zonas francas, bodegas logísticas, sistemas CI NSR-10, permisos CAR Cundinamarca.', url: 'https://ingenieriabernal.co/sabana-occidente' },
  { path: 'sabana-norte', title: 'Ingeniería Hidráulica Sabana Norte — BIC Bernal', desc: 'Tocancipá, Zipaquirá, Cajicá, Chía, Sopó. Mayor crecimiento industrial norte de Bogotá. Estudios riesgo hídrico planes parciales, sistemas CI NSR-10, formulación regalías SGR.', url: 'https://ingenieriabernal.co/sabana-norte' },
  { path: 'boyaca-corredor', title: 'Ingeniería Hidráulica Corredor Boyacá — BIC Bernal', desc: 'Duitama, Sogamoso, Paipa, Nobsa, Tibasosa. Corredor acerero y turístico. Diseño hidrosanitario industrial, sistemas CI plantas industriales, acueducto y alcantarillado.', url: 'https://ingenieriabernal.co/boyaca-corredor' },
  { path: 'huila-neiva', title: 'Ingeniería Hidráulica Huila — BIC Bernal Ingeniería', desc: 'Neiva, Pitalito, Campoalegre, Garzón. Regalías petroleras e hidroeléctricas. Diseño acueducto y alcantarillado, estudios inundación río Magdalena, formulación proyectos MGA-Web.', url: 'https://ingenieriabernal.co/huila-neiva' },
  { path: 'bucaramanga-area', title: 'Ingeniería Hidráulica Área Metropolitana Bucaramanga — BIC', desc: 'Floridablanca, Girón, Piedecuesta, Barrancabermeja. DNP: Floridablanca mejor evaluada de Colombia. Diseño hidrosanitario, sistemas CI NSR-10, estudios riesgo hídrico, CDMB.', url: 'https://ingenieriabernal.co/bucaramanga-area' },
  { path: 'santander-sur', title: 'Ingeniería Hidráulica Santander Sur — BIC Bernal', desc: 'Barbosa, Socorro, San Gil, Barichara, Charalá. Turismo activo, agroindustria. Estudios riesgo hídrico, diseño acueducto rural, formulación proyectos regalías SGR.', url: 'https://ingenieriabernal.co/santander-sur' },
  { path: 'antioquia-suroeste', title: 'Ingeniería Hidráulica Suroeste Antioqueño — BIC Bernal', desc: 'Andes, La Pintada, Jardín, Jericó, Valparaíso. Autopistas 4G Pacífico 1 y 2. Estudios riesgo hídrico infraestructura vial, acueducto, gestión torrencialidad. BIC Bernal.', url: 'https://ingenieriabernal.co/antioquia-suroeste' },
  { path: 'costa-caribe', title: 'Ingeniería Hidráulica Costa Caribe — BIC Bernal', desc: 'Montería, Sincelejo, Valledupar, Riohacha. Expansión urbana activa en capitales intermedias. Diseño acueducto, formulación proyectos regalías MGA-Web, gestión riesgo hídrico costero.', url: 'https://ingenieriabernal.co/costa-caribe' },
  { path: 'llanos-orinoquia', title: 'Ingeniería Hidráulica Llanos y Orinoquía — BIC Bernal', desc: 'Villavicencio, Yopal, Acacías, Granada, Aguazul. Regalías petroleras y gasíferas. Formulación proyectos MGA-Web, diseño acueducto rural, estudios inundación llanura aluvial.', url: 'https://ingenieriabernal.co/llanos-orinoquia' },

  // Páginas ingeniería por ciudad (RegionalPage)
  { path: 'ingenieria-bogota', title: 'Ingeniería Hidráulica Bogotá | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores ofrece consultoría en ingeniería hidráulica en Bogotá y Cundinamarca: diseño hidráulico, estudios hidrológicos HEC-RAS, acueductos, geotecnia y PSMV. COPNIA 17202-313228.', url: 'https://ingenieriabernal.co/ingenieria-bogota' },
  { path: 'ingenieria-medellin', title: 'Ingeniería Hidráulica Medellín | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Medellín y Antioquia. BIC ofrece diseño hidráulico, modelación HEC-RAS, acueductos y alcantarillado, geotecnia y PSMV. Equipo multidisciplinario · UNAL · COPNIA.', url: 'https://ingenieriabernal.co/ingenieria-medellin' },
  { path: 'ingenieria-cali', title: 'Ingeniería Hidráulica Cali | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en Cali y Valle del Cauca: ingeniería hidráulica, estudios hidrológicos, diseño de acueductos y alcantarillado, geotecnia y PSMV. 10+ años de experiencia en Colombia.', url: 'https://ingenieriabernal.co/ingenieria-cali' },
  { path: 'ingenieria-manizales', title: 'Ingeniería Hidráulica Manizales | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores, con sede en Manizales, Caldas: consultoría en ingeniería hidráulica, diseño hidrosanitario NSR-10, modelación HEC-RAS, acueductos Res. 0330/2017, geotecnia y PSMV.', url: 'https://ingenieriabernal.co/ingenieria-manizales' },
  { path: 'ingenieria-bucaramanga', title: 'Ingeniería Hidráulica Bucaramanga | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Bucaramanga y Santander. BIC ofrece diseño hidráulico, estudios hidrológicos HEC-RAS, acueductos, alcantarillado, geotecnia y PSMV. COPNIA · UNAL.', url: 'https://ingenieriabernal.co/ingenieria-bucaramanga' },
  { path: 'ingenieria-barranquilla', title: 'Ingeniería Hidráulica Barranquilla | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en Barranquilla y el Atlántico: ingeniería hidráulica, estudios de inundación, acueductos y alcantarillado, geotecnia, PSMV y gestión del riesgo hídrico costero.', url: 'https://ingenieriabernal.co/ingenieria-barranquilla' },
  { path: 'ingenieria-eje-cafetero', title: 'Ingeniería Hidráulica Eje Cafetero | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en el Eje Cafetero (Pereira, Armenia, Dosquebradas): consultoría hidráulica, diseño hidrosanitario NSR-10, estudios Decreto 1807, acueductos, geotecnia y PSMV.', url: 'https://ingenieriabernal.co/ingenieria-eje-cafetero' },
  { path: 'ingenieria-antioquia', title: 'Ingeniería Hidráulica Antioquia | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Antioquia. BIC ofrece diseño hidráulico, modelación HEC-RAS, estudios hidrológicos, acueductos Res. 0330/2017, geotecnia, PSMV y gestión del riesgo hídrico.', url: 'https://ingenieriabernal.co/ingenieria-antioquia' },

  // Blog posts
  { path: 'blog/suds-sistemas-drenaje-sostenible-colombia', title: 'SUDS en Colombia: Drenaje Sostenible para Ciudades de Montaña | BIC', desc: 'Conozca cómo los Sistemas Urbanos de Drenaje Sostenible (SUDS) reducen inundaciones en ciudades colombianas de montaña. Marco normativo, tipologías y casos reales.', url: 'https://ingenieriabernal.co/blog/suds-sistemas-drenaje-sostenible-colombia' },
  { path: 'blog/costos-obras-hidraulicas-colombia-2026', title: 'Costos de Obras Hidráulicas Colombia 2026: APU y Tendencias | BIC', desc: 'Guía actualizada de costos unitarios para redes de acueducto, alcantarillado, drenaje urbano y CI en Manizales y el Eje Cafetero 2026.', url: 'https://ingenieriabernal.co/blog/costos-obras-hidraulicas-colombia-2026' },
  { path: 'blog/cambios-normativos-ingenieria-hidraulica-2026', title: 'Cambios Normativos Ingeniería Hidráulica 2026 | BIC Bernal Ingeniería', desc: 'Análisis de actualizaciones normativas en ingeniería hidráulica Colombia 2026. Resolución 0330, RAS 2017, Decreto 1807. Impacto en proyectos y oportunidades.', url: 'https://ingenieriabernal.co/blog/cambios-normativos-ingenieria-hidraulica-2026' },
  { path: 'blog/riesgo-hidraulico-ciudades-densas', title: 'Riesgo Hidráulico en Ciudades Densas: Desarrollos Sostenibles | BIC', desc: 'Estrategias técnicas para gestión del riesgo hídrico en Manizales, Dosquebradas y Pereira. Modelación HEC-RAS, Decreto 1807, sistemas SUDS. Casos reales.', url: 'https://ingenieriabernal.co/blog/riesgo-hidraulico-ciudades-densas' },
  { path: 'blog/hec-ras-2d-colombia', title: 'HEC-RAS 2D en Colombia: Guía Práctica para Consultores Hidráulicos | BIC', desc: 'Guía técnica HEC-RAS 2D para estudios de amenaza por inundación exigidos por el Decreto 1807/2014 en Colombia. Metodología, casos reales y ventajas sobre el modelo 1D.', url: 'https://ingenieriabernal.co/blog/hec-ras-2d-colombia' },
  { path: 'blog/proyectos-regalias-agua-saneamiento', title: 'Formular Proyectos de Agua con Regalías en Colombia — MGA-Web | BIC', desc: 'Guía paso a paso para formular proyectos de agua potable y saneamiento en MGA-Web del DNP para el SGR. Errores comunes, requisitos y casos reales aprobados.', url: 'https://ingenieriabernal.co/blog/proyectos-regalias-agua-saneamiento' },
  { path: 'blog/nsr-10-sistemas-contra-incendios', title: 'NSR-10 Capítulos J y K: Sistemas Contra Incendios Colombia | BIC', desc: 'Guía técnica completa sobre NSR-10 Caps. J y K para sistemas contra incendios en edificaciones colombianas. NTC 1500, 1669, 2301. Casos reales.', url: 'https://ingenieriabernal.co/blog/nsr-10-sistemas-contra-incendios' },
  { path: 'blog/irca-municipio-colombia', title: 'Cómo bajar el IRCA de un municipio en Colombia | BIC Bernal Ingeniería', desc: 'Aprenda qué es el IRCA, por qué sube, cuáles son las causas más comunes en municipios colombianos y qué pasos concretos puede tomar para reducirlo. Información técnica con respaldo normativo.', url: 'https://ingenieriabernal.co/blog/irca-municipio-colombia' },
  { path: 'blog/mga-web-regalias-agua-potable', title: 'Formulación proyectos agua potable con regalías y MGA Web Colombia | BIC', desc: 'Guía práctica para alcaldes, secretarios de planeación y gestores del SGR sobre cómo formular proyectos de acueducto en la MGA Web sin cometer los errores que hacen devolver los proyectos.', url: 'https://ingenieriabernal.co/blog/mga-web-regalias-agua-potable' },
  { path: 'blog/hec-ras-2d-modelacion-hidraulica-colombia', title: 'Contratar modelación hidráulica HEC-RAS 2D en Colombia | BIC Bernal Ingeniería', desc: 'Guía técnica para constructoras, promotores e ingenieros sobre qué es la modelación HEC-RAS 2D, cuándo es obligatoria en Colombia y qué debe incluir un modelo bien hecho.', url: 'https://ingenieriabernal.co/blog/hec-ras-2d-modelacion-hidraulica-colombia' },
  { path: 'blog/acueducto-rural-colombia', title: 'Diseño de Acueductos Rurales en Colombia: Guía Técnica | BIC', desc: 'Guía completa para el diseño de sistemas de acueducto rural en Colombia. Normativa RAS 2017, captación, conducción, tratamiento y distribución para comunidades rurales.', url: 'https://ingenieriabernal.co/blog/acueducto-rural-colombia' },
  { path: 'blog/ptap-colombia', title: 'PTAP en Colombia: Diseño y Normativa para Plantas de Agua Potable | BIC', desc: 'Todo lo que necesita saber sobre el diseño de Plantas de Tratamiento de Agua Potable (PTAP) en Colombia. Procesos, normativa RAS, INEN y casos reales.', url: 'https://ingenieriabernal.co/blog/ptap-colombia' },
  { path: 'blog/redes-hidrosanitarias-colombia', title: 'Redes Hidrosanitarias en Colombia: Diseño según NSR-10 y RAS | BIC', desc: 'Diseño de redes hidrosanitarias en Colombia para proyectos de vivienda e industria. Normativa NSR-10, NTC 1500, RAS 2017. Memorias, planos y especificaciones técnicas.', url: 'https://ingenieriabernal.co/blog/redes-hidrosanitarias-colombia' },
  { path: 'blog/sistemas-contra-incendio-nsr10', title: 'Sistemas Contra Incendio NSR-10: Diseño y Cálculo en Colombia | BIC', desc: 'Diseño de sistemas contra incendio según NSR-10 capítulos J y K en Colombia. Rociadores, hidrantes, gabinetes y detección. Proyectos industriales y comerciales.', url: 'https://ingenieriabernal.co/blog/sistemas-contra-incendio-nsr10' },
  { path: 'blog/interventoria-hidraulica-colombia', title: 'Interventoría de Obras Hidráulicas en Colombia | BIC Bernal Ingeniería', desc: 'Servicios de interventoría técnica para obras hidráulicas en Colombia: acueductos, alcantarillados, PTAR y obras de drenaje. Supervisión, control y calidad.', url: 'https://ingenieriabernal.co/blog/interventoria-hidraulica-colombia' },
  { path: 'blog/alcantarillado-pluvial-colombia', title: 'Diseño de Alcantarillado Pluvial en Colombia: Normativa y Cálculo | BIC', desc: 'Guía técnica para diseño de sistemas de alcantarillado pluvial en Colombia según RAS 2017 y Decreto 1807. Caudales de diseño, cunetas, colectores y estructuras especiales.', url: 'https://ingenieriabernal.co/blog/alcantarillado-pluvial-colombia' },
  { path: 'blog/epanet-colombia-acueducto', title: 'EPANET para Diseño de Acueductos en Colombia | BIC Bernal Ingeniería', desc: 'Uso de EPANET en proyectos de acueducto en Colombia. Modelación hidráulica de redes de distribución, análisis de presiones, caudales y calidad del agua. Casos reales.', url: 'https://ingenieriabernal.co/blog/epanet-colombia-acueducto' },
  { path: 'blog/bocatoma-lateral-colombia', title: 'Diseño de Bocatomas Laterales en Colombia: Guía Técnica | BIC', desc: 'Guía completa para el diseño de bocatomas laterales en ríos colombianos. Cálculo de caudales, rejillas, canal de aducción y desarenador según normas colombianas.', url: 'https://ingenieriabernal.co/blog/bocatoma-lateral-colombia' },
  { path: 'blog/ras-2000-colombia', title: 'RAS 2017 en Colombia: Reglamento de Agua y Saneamiento Básico | BIC', desc: 'Guía práctica del Reglamento Técnico del Sector de Agua Potable y Saneamiento Básico (RAS) en Colombia. Aplicación en diseño de acueductos, alcantarillados y PTAR.', url: 'https://ingenieriabernal.co/blog/ras-2000-colombia' },
  { path: 'blog/ley-1523-riesgo-colombia', title: 'Ley 1523 de 2012: Gestión del Riesgo de Desastres en Colombia | BIC', desc: 'Análisis de la Ley 1523 de 2012 y su aplicación en proyectos de ingeniería en Colombia. Gestión del riesgo, planes municipales y responsabilidades de los entes territoriales.', url: 'https://ingenieriabernal.co/blog/ley-1523-riesgo-colombia' },
  { path: 'blog/nsr10-titulo-j-incendios-colombia', title: 'NSR-10 Título J: Requisitos de Protección Contra Incendios | BIC', desc: 'Guía técnica del Título J de la NSR-10 sobre protección contra incendios en Colombia. Sistemas activos, pasivos, rutas de evacuación y normativa complementaria NTC.', url: 'https://ingenieriabernal.co/blog/nsr10-titulo-j-incendios-colombia' },
  { path: 'blog/pomca-colombia', title: 'POMCA en Colombia: Plan de Ordenación y Manejo de Cuencas | BIC', desc: 'Qué es el POMCA, cómo afecta los proyectos de ingeniería en Colombia y cómo gestionar permisos en cuencas reglamentadas. Impacto en licencias ambientales y construcción.', url: 'https://ingenieriabernal.co/blog/pomca-colombia' },
  { path: 'blog/decreto-1575-agua-colombia', title: 'Decreto 1575 de 2007: Calidad del Agua Potable en Colombia | BIC', desc: 'Análisis del Decreto 1575 de 2007 y su relación con el diseño de PTAP en Colombia. Parámetros de calidad, IRCA y responsabilidades de prestadores del servicio de acueducto.', url: 'https://ingenieriabernal.co/blog/decreto-1575-agua-colombia' },
  { path: 'blog/licencia-ambiental-anla-colombia', title: 'Licencia Ambiental ANLA en Colombia: Guía para Proyectos de Ingeniería | BIC', desc: 'Proceso de obtención de licencia ambiental ante la ANLA en Colombia. Estudios requeridos, tiempos, documentación y estrategias para proyectos hidráulicos exitosos.', url: 'https://ingenieriabernal.co/blog/licencia-ambiental-anla-colombia' },
  { path: 'blog/contratacion-publica-ingenieria-colombia', title: 'Contratación Pública de Ingeniería en Colombia: SECOP y Licitaciones | BIC', desc: 'Guía para participar en licitaciones de ingeniería en Colombia a través del SECOP. Requisitos, propuestas técnicas y económicas, y estrategias para consultores independientes.', url: 'https://ingenieriabernal.co/blog/contratacion-publica-ingenieria-colombia' },
  { path: 'blog/riesgo-inundacion-eje-cafetero', title: 'Riesgo de Inundación en el Eje Cafetero: Estudios y Soluciones | BIC', desc: 'Análisis del riesgo de inundación en Manizales, Pereira y Armenia. Modelación hidráulica, medidas de mitigación y cumplimiento del Decreto 1807 para el Eje Cafetero.', url: 'https://ingenieriabernal.co/blog/riesgo-inundacion-eje-cafetero' },
  { path: 'blog/estabilidad-taludes-eje-cafetero', title: 'Estabilidad de Taludes en el Eje Cafetero: Análisis y Diseño | BIC', desc: 'Evaluación y diseño de obras de estabilización de taludes en el Eje Cafetero colombiano. Suelos volcánicos, lluvias intensas, normas NSR-10 y casos reales en Manizales.', url: 'https://ingenieriabernal.co/blog/estabilidad-taludes-eje-cafetero' },
  { path: 'blog/regalias-acueducto-colombia', title: 'Proyectos de Acueducto con Regalías en Colombia: Formulación MGA | BIC', desc: 'Cómo formular y ejecutar proyectos de acueducto financiados con regalías del SGR en Colombia. MGA Web, DNP, requisitos técnicos y errores frecuentes.', url: 'https://ingenieriabernal.co/blog/regalias-acueducto-colombia' },
  { path: 'blog/caso-estudio-acueducto-rural', title: 'Caso de Estudio: Diseño de Acueducto Rural en el Eje Cafetero | BIC', desc: 'Caso real de diseño de acueducto rural en Caldas, Colombia. Captación, conducción, PTAP y red de distribución para 300 familias. Lecciones aprendidas y resultados.', url: 'https://ingenieriabernal.co/blog/caso-estudio-acueducto-rural' },
  { path: 'blog/plan-mejoramiento-irca-colombia', title: 'Plan de Mejoramiento de IRCA en Municipios Colombianos | BIC', desc: 'Estrategia técnica para reducir el IRCA en municipios de Colombia. Diagnóstico del sistema de acueducto, mejoras en PTAP, red de distribución y gestión del operador.', url: 'https://ingenieriabernal.co/blog/plan-mejoramiento-irca-colombia' },
  { path: 'blog/contratar-consultoria-hidraulica-colombia', title: 'Cómo Contratar Consultoría Hidráulica en Colombia | BIC Bernal Ingeniería', desc: 'Guía para constructoras, alcaldías y promotores sobre cómo contratar consultoría de ingeniería hidráulica en Colombia. Criterios de selección, propuestas y entregables esperados.', url: 'https://ingenieriabernal.co/blog/contratar-consultoria-hidraulica-colombia' },
  { path: 'blog/bocatoma-caudal-riego-colombia', title: '¿Cuánto caudal necesita una bocatoma para riego en Colombia? | BIC', desc: 'Guía técnica para calcular el caudal de diseño de una bocatoma para riego en Colombia. Metodología, concesiones de agua, IDEAM y trámites ante la CAR o Corpocaldas.', url: 'https://ingenieriabernal.co/blog/bocatoma-caudal-riego-colombia' },
  { path: 'blog/estudio-hidrologico-decreto-1807', title: 'Estudio Hidrológico para Decreto 1807: Qué incluye y cuánto cuesta | BIC', desc: 'Todo lo que necesita saber sobre el estudio hidrológico exigido por el Decreto 1807 en Colombia. Componentes, plazos, costos y cómo elegir un consultor competente.', url: 'https://ingenieriabernal.co/blog/estudio-hidrologico-decreto-1807' },
  { path: 'blog/hec-ras-1d-vs-2d-colombia', title: 'HEC-RAS 1D vs 2D en Colombia: ¿Cuál modelo necesita su proyecto? | BIC', desc: 'Comparativa técnica entre modelación HEC-RAS 1D y 2D para proyectos en Colombia. Cuándo usar cada uno, costos, tiempos y requisitos del Decreto 1807 y las CAR.', url: 'https://ingenieriabernal.co/blog/hec-ras-1d-vs-2d-colombia' },
  { path: 'blog/ptar-industrial-colombia', title: 'PTAR Industrial en Colombia: Diseño, Permisos y Costos | BIC', desc: 'Guía completa sobre plantas de tratamiento de aguas residuales industriales en Colombia. Normativa TULSMA, vertimientos, diseño de procesos y trámites ante la autoridad ambiental.', url: 'https://ingenieriabernal.co/blog/ptar-industrial-colombia' },
  { path: 'blog/ingeniero-hidraulico-para-mi-proyecto', title: '¿Necesito un ingeniero hidráulico para mi proyecto en Colombia? | BIC', desc: 'Descubra cuándo es obligatorio contratar un ingeniero hidráulico en Colombia, qué estudios debe entregar y cómo encontrar el consultor adecuado para su tipo de proyecto.', url: 'https://ingenieriabernal.co/blog/ingeniero-hidraulico-para-mi-proyecto' },
  { path: 'blog/retiro-quebrada-construccion-colombia', title: 'Retiro de Quebrada para Construir en Colombia: Normas y Trámites | BIC', desc: 'Guía sobre retiros de quebradas y cuerpos de agua para construcción en Colombia. Decreto 1807, POT, licencias urbanismo y cómo gestionar un predio en zona de retiro.', url: 'https://ingenieriabernal.co/blog/retiro-quebrada-construccion-colombia' },
  { path: 'blog/que-necesito-para-urbanizar-un-lote-colombia', title: '¿Qué estudios necesito para urbanizar un lote en Colombia? | BIC', desc: 'Lista completa de estudios técnicos requeridos para obtener licencia de urbanismo en Colombia: hidrología, hidráulica, geotecnia, redes y más. Guía por etapas.', url: 'https://ingenieriabernal.co/blog/que-necesito-para-urbanizar-un-lote-colombia' },
  { path: 'blog/estudios-car-corpocaldas-colombia', title: 'Estudios técnicos para trámites ante CAR y Corpocaldas | BIC', desc: 'Qué estudios pide la CAR o Corpocaldas para permisos de aprovechamiento hídrico, vertimientos y concesiones de agua en Colombia. Guía práctica con requisitos actualizados.', url: 'https://ingenieriabernal.co/blog/estudios-car-corpocaldas-colombia' },
  { path: 'blog/cuanto-cuesta-estudio-hidrologico', title: '¿Cuánto cuesta un estudio hidrológico en Colombia 2025? | BIC', desc: 'Rangos de precio reales para estudios hidrológicos en Colombia: Decreto 1807, concesiones, vías y POMCA. Factores que afectan el costo y cómo obtener una propuesta justa.', url: 'https://ingenieriabernal.co/blog/cuanto-cuesta-estudio-hidrologico' },
  { path: 'blog/requisitos-ptar-licencia-construccion', title: 'Requisitos PTAR para licencia de construcción en Colombia | BIC', desc: 'Qué exige la curaduría para una PTAR en la licencia de construcción en Colombia: memoria técnica, permiso de vertimientos y norma aplicable (RAS 2017, Resolución 0631).', url: 'https://ingenieriabernal.co/blog/requisitos-ptar-licencia-construccion' },
  { path: 'blog/estudio-hidraulico-urbanizacion', title: '¿Qué incluye un estudio hidráulico para urbanización en Colombia? | BIC', desc: 'Componentes del estudio hidráulico para licencia de urbanismo: redes pluviales y sanitarias, amenaza hídrica Decreto 1807 y verificación de conexión a red pública.', url: 'https://ingenieriabernal.co/blog/estudio-hidraulico-urbanizacion' },
  { path: 'blog/calcular-caudal-diseno-alcantarillado', title: 'Cómo calcular el caudal de diseño para alcantarillado en Colombia | BIC', desc: 'Método racional y SCS-CN para el caudal de diseño en alcantarillado pluvial y sanitario según la Resolución 0330/2017. Ejemplos prácticos y parámetros del RAS.', url: 'https://ingenieriabernal.co/blog/calcular-caudal-diseno-alcantarillado' },
  { path: 'blog/diseno-ptap-municipio-costos', title: 'Tiempo y costos de un diseño PTAP para municipio en Colombia | BIC', desc: 'Cuánto cuesta y cuánto tarda el diseño de una PTAP para municipio en Colombia: rangos por capacidad en L/s, fases del diseño y entregables según el RAS 2017.', url: 'https://ingenieriabernal.co/blog/diseno-ptap-municipio-costos' },
  { path: 'blog/modelacion-hec-ras-colombia', title: 'Modelación HEC-RAS en Colombia: guía para proyectos | BIC', desc: 'Guía práctica de HEC-RAS para proyectos en Colombia: cuándo se exige, diferencia 1D y 2D, datos de entrada y resultados para el Decreto 1807 y trámites ante la CAR.', url: 'https://ingenieriabernal.co/blog/modelacion-hec-ras-colombia' },
  { path: 'blog/plan-manejo-aguas-lluvias-colombia', title: '¿Cuándo se requiere plan de manejo de aguas lluvias en Colombia? | BIC', desc: 'En qué proyectos exige Colombia un plan de manejo de aguas lluvias: urbanizaciones, parques industriales, SUDS y POT. Qué debe contener y cómo cumplir el RAS 2017.', url: 'https://ingenieriabernal.co/blog/plan-manejo-aguas-lluvias-colombia' },
  { path: 'blog/diferencias-ptar-ptap', title: 'Diferencias entre PTAR y PTAP en Colombia: ¿cuál necesito? | BIC', desc: 'Explicación clara de PTAR vs PTAP en Colombia: propósito, norma aplicable, permiso requerido y en qué casos su proyecto necesita una, la otra o ambas.', url: 'https://ingenieriabernal.co/blog/diferencias-ptar-ptap' },
  { path: 'blog/permiso-vertimientos-colombia', title: 'Requisitos para permiso de vertimientos en Colombia | BIC', desc: 'Documentos, pasos y tiempos para el permiso de vertimientos ante la CAR en Colombia. Decreto 1076/2015, Resolución 0631/2015 y consecuencias de operar sin permiso.', url: 'https://ingenieriabernal.co/blog/permiso-vertimientos-colombia' },
  { path: 'blog/estudio-amenaza-inundacion', title: 'Estudio de amenaza por inundación en Colombia: paso a paso | BIC', desc: 'Metodología completa del estudio de amenaza por inundación: datos, análisis hidrológico, modelación HEC-RAS, mapa de amenaza y entregables para curaduría y CAR.', url: 'https://ingenieriabernal.co/blog/estudio-amenaza-inundacion' },
  { path: 'blog/socavacion-puentes-hec18-colombia', title: 'Socavación de puentes con HEC-18 en Colombia: metodología y costos 2026 | BIC', desc: 'Análisis de socavación en puentes con HEC-18 y HEC-RAS en Colombia. Tipos de socavación, normativa INVIAS y costos.', url: 'https://ingenieriabernal.co/blog/socavacion-puentes-hec18-colombia' },
  { path: 'blog/condicion-aguas-abajo-hec-ras', title: 'Condición de aguas abajo en HEC-RAS: régimen subcrítico y supercrítico | BIC', desc: 'Cómo elegir la condición de borde aguas abajo en HEC-RAS según el régimen de flujo. Guía completa con ejemplos colombianos.', url: 'https://ingenieriabernal.co/blog/condicion-aguas-abajo-hec-ras' },
  { path: 'blog/modelacion-avenidas-torrenciales-colombia', title: 'Modelación de avenidas torrenciales en Colombia: metodología SGC y RAMMS | BIC', desc: 'Zonificación de amenaza por avenidas torrenciales en Colombia. Metodología SGC, software RAMMS y HEC-RAS, Eje Cafetero.', url: 'https://ingenieriabernal.co/blog/modelacion-avenidas-torrenciales-colombia' },
  // Batch G — Semana 1 calendario editorial
  { path: 'blog/diseno-hidraulico-urbanizaciones', title: 'Diseño hidráulico de urbanizaciones en Colombia: guía completa 2026 | BIC', desc: 'Proceso paso a paso para el diseño hidráulico de urbanizaciones: redes hidrosanitarias, alcantarillado pluvial, amenaza Decreto 1807 y costos 2026.', url: 'https://ingenieriabernal.co/blog/diseno-hidraulico-urbanizaciones' },
  { path: 'blog/hec-ras-modelado-fluvial-introduccion', title: 'HEC-RAS para ingenieros: introducción al modelado fluvial paso a paso | BIC', desc: 'Tutorial de HEC-RAS desde cero: descarga, tipos de modelos, datos necesarios, 5 pasos para el primer modelo y errores frecuentes en Colombia.', url: 'https://ingenieriabernal.co/blog/hec-ras-modelado-fluvial-introduccion' },
  { path: 'blog/caso-red-hidrosanitaria-vivienda', title: 'Caso real: diseño de red hidrosanitaria en vivienda unifamiliar (Colombia) | BIC', desc: 'Caso Armenia Quindío, 180 m², 2 pisos: método Hunter, dimensionamiento DN, costos reales 2026 y presupuesto completo diseño e instalación.', url: 'https://ingenieriabernal.co/blog/caso-red-hidrosanitaria-vivienda' },
  { path: 'blog/estudio-hidrologico-cuencas-paso-a-paso', title: 'Estudio hidrológico de cuencas en Colombia: metodología paso a paso 2026 | BIC', desc: 'Cómo se elabora un estudio hidrológico de cuencas: delimitación, morfometría, análisis estadístico, HEC-HMS y regionalización para el Decreto 1807 y el RAS 2017.', url: 'https://ingenieriabernal.co/blog/estudio-hidrologico-cuencas-paso-a-paso' },
  { path: 'blog/normativa-icontec-hidraulica-colombia', title: 'Normas ICONTEC para hidráulica en Colombia: cuáles aplican y cuándo exigirlas | BIC', desc: 'Guía de las NTC aplicables al diseño hidráulico en Colombia: NTC 3722, NTC 1062, NTC 1462, NTC 1500 y más. Cuándo son obligatorias y cómo verificarlas en obra.', url: 'https://ingenieriabernal.co/blog/normativa-icontec-hidraulica-colombia' },
  { path: 'blog/tuberias-pvc-vs-pe-colombia', title: 'Tuberías PVC vs PE en Colombia: comparativa técnica para redes hidrosanitarias 2026 | BIC', desc: 'Diferencias entre PVC y HDPE para acueducto y alcantarillado: resistencia mecánica, costos 2026, facilidad de instalación y cuándo usar cada material según el RAS 2017.', url: 'https://ingenieriabernal.co/blog/tuberias-pvc-vs-pe-colombia' },
  // Batch H — Alta prioridad Mayo 2026
  { path: 'blog/calculo-caudal-diseno-acueducto-rural-colombia', title: 'Cómo calcular el caudal de diseño para un acueducto rural en Colombia (RAS 2017) | BIC', desc: 'Guía práctica con fórmulas y ejemplos reales para calcular QMD, QMMD y QMH según el RAS 2017. Dotaciones, factores K1 y K2, período de diseño 25 años.', url: 'https://ingenieriabernal.co/blog/calculo-caudal-diseno-acueducto-rural-colombia' },
  { path: 'blog/tramitar-concesion-aguas-colombia-guia', title: 'Cómo tramitar una concesión de aguas en Colombia: guía paso a paso 2026 | BIC', desc: 'Requisitos, tiempos y costos para obtener concesión de aguas en Colombia. Decreto 1076/2015, solicitud ante CAR/CORPOCALDAS, documentos técnicos requeridos.', url: 'https://ingenieriabernal.co/blog/tramitar-concesion-aguas-colombia-guia' },
  { path: 'blog/cuanto-cuesta-diseno-acueducto-colombia-2026', title: '¿Cuánto cuesta el diseño de un acueducto en Colombia en 2026? | BIC', desc: 'Rangos de precio reales para diseño de acueductos en Colombia: desde estudios básicos hasta diseños integrales para parcelaciones y municipios. Factores que afectan el costo.', url: 'https://ingenieriabernal.co/blog/cuanto-cuesta-diseno-acueducto-colombia-2026' },
  { path: 'blog/requisitos-car-acueducto-veredal-colombia', title: 'Qué exige la CAR para aprobar un acueducto veredal en Colombia | BIC', desc: 'Documentos técnicos, estudios y trámites ambientales requeridos ante la CAR para legalizar un acueducto comunitario o veredal. RAS 2017, Decreto 1575/2007.', url: 'https://ingenieriabernal.co/blog/requisitos-car-acueducto-veredal-colombia' },
  { path: 'blog/como-formular-proyecto-agua-potable-sgr-colombia', title: 'Cómo formular un proyecto de agua potable para el SGR en Colombia | BIC', desc: 'Guía para alcaldías y municipios: cómo estructurar un proyecto de acueducto o agua potable en el Sistema General de Regalías usando MGA-Web y Gesproy.', url: 'https://ingenieriabernal.co/blog/como-formular-proyecto-agua-potable-sgr-colombia' },
  // Batch I — Mayo 2026 (PTAP/PTAR, inundabilidad, CI NSR-10, POMCA, interventoría)
  { path: 'blog/diferencia-ptap-ptar-colombia', title: '¿Cuál es la diferencia entre PTAP y PTAR en Colombia? | BIC', desc: 'Aprende la diferencia entre planta de tratamiento de agua potable (PTAP) y planta de tratamiento de aguas residuales (PTAR) según el RAS 2017. Guía técnica colombiana.', url: 'https://ingenieriabernal.co/blog/diferencia-ptap-ptar-colombia' },
  { path: 'blog/estudio-inundabilidad-lote-colombia', title: 'Estudio de inundabilidad para lote en Colombia: qué es y cómo tramitarlo | BIC', desc: 'Guía completa del estudio de inundabilidad en Colombia: cuándo se exige, qué contiene, normas (Decreto 1807/2014, RAS), costos y plazos. Para constructores y alcaldías.', url: 'https://ingenieriabernal.co/blog/estudio-inundabilidad-lote-colombia' },
  { path: 'blog/diseno-red-contra-incendio-nsr10-colombia', title: 'Diseño de red contra incendio NSR-10 en Colombia: requisitos y normas | BIC', desc: 'Todo sobre el diseño de redes contra incendio en Colombia según NSR-10 Título J, NTC 1669, NTC 2301 y NFPA 13. Requisitos, cálculo hidráulico y tramitación.', url: 'https://ingenieriabernal.co/blog/diseno-red-contra-incendio-nsr10-colombia' },
  { path: 'blog/que-es-pomca-colombia-para-que-sirve', title: '¿Qué es un POMCA en Colombia y para qué sirve? | BIC', desc: 'Explicación clara de qué es un POMCA (Plan de Ordenación y Manejo de Cuencas Hidrográficas) en Colombia, para qué sirve, quién lo formula y cómo afecta los proyectos.', url: 'https://ingenieriabernal.co/blog/que-es-pomca-colombia-para-que-sirve' },
  { path: 'blog/interventoria-obras-hidraulicas-colombia', title: 'Interventoría de obras hidráulicas en Colombia: qué es y cuánto cuesta | BIC', desc: 'Guía completa sobre interventoría de obras hidráulicas en Colombia: obligatoriedad (Ley 80, Ley 1474, SGR), funciones, costos típicos 8-15% y cómo seleccionar un interventor.', url: 'https://ingenieriabernal.co/blog/interventoria-obras-hidraulicas-colombia' },
  // Batch J — Mayo 2026 (costos PTAP/PTAR, licencias acueducto, vida útil, concesión aguas)
  { path: 'blog/cuanto-cuesta-ptap-colombia-2026', title: '¿Cuánto cuesta una planta de tratamiento de agua potable en Colombia en 2026? | BIC', desc: 'Guía de costos de PTAP en Colombia 2026: desde sistemas compactos hasta plantas municipales. Incluye rangos por capacidad, factores que afectan el precio y cómo presupuestar.', url: 'https://ingenieriabernal.co/blog/cuanto-cuesta-ptap-colombia-2026' },
  { path: 'blog/cuanto-cuesta-ptar-aguas-residuales-colombia', title: '¿Cuánto cuesta una PTAR en Colombia? Costos de plantas de aguas residuales 2026 | BIC', desc: 'Costos reales de plantas de tratamiento de aguas residuales (PTAR) en Colombia 2026. Desde sistemas para pequeñas poblaciones hasta municipios. RAS Título E y Res. 0631.', url: 'https://ingenieriabernal.co/blog/cuanto-cuesta-ptar-aguas-residuales-colombia' },
  { path: 'blog/tramitar-licencia-construccion-acueducto-colombia', title: 'Cómo tramitar licencia de construcción para acueducto en Colombia | BIC', desc: 'Guía paso a paso para tramitar la licencia de construcción de un acueducto en Colombia: documentos, entidades, plazos y costos. Decreto 1077/2015 y RAS 2017.', url: 'https://ingenieriabernal.co/blog/tramitar-licencia-construccion-acueducto-colombia' },
  { path: 'blog/vida-util-acueducto-rural-colombia', title: 'Vida útil de un acueducto rural en Colombia: qué factores la determinan | BIC', desc: 'Aprende cuánto dura un acueducto rural en Colombia, qué determina su vida útil según el RAS 2017, y cómo el diseño y el mantenimiento influyen en que dure 20-25 años o más.', url: 'https://ingenieriabernal.co/blog/vida-util-acueducto-rural-colombia' },
  { path: 'blog/que-es-concesion-de-aguas-colombia', title: '¿Qué es una concesión de aguas en Colombia y para qué sirve? | BIC', desc: 'Explicación clara de qué es una concesión de aguas en Colombia, quién la otorga, para qué sirve, plazos y cómo tramitarla. Guía para no ingenieros.', url: 'https://ingenieriabernal.co/blog/que-es-concesion-de-aguas-colombia' },
  // Batch K — Mayo 2026 (acueducto multiveredal, estudio hidrológico, SGR paso a paso, bocatoma vs captación, cuándo contratar ingeniero hidráulico)
  { path: 'blog/acueducto-multiveredal-colombia', title: 'Acueducto multiveredal en Colombia: qué es, cómo diseñarlo y financiarlo | BIC', desc: 'Guía completa sobre acueductos multiveredales en Colombia: definición, diseño según RAS 2017, requisitos de asociación de usuarios, financiación SGR y Findeter.', url: 'https://ingenieriabernal.co/blog/acueducto-multiveredal-colombia' },
  { path: 'blog/estudio-hidrologico-colombia-que-es', title: '¿Qué es un estudio hidrológico en Colombia y cuándo se necesita? | BIC', desc: 'Guía clara sobre estudios hidrológicos en Colombia: qué son, cuándo los exigen las CARs y alcaldías, qué contienen, qué normas aplican y cuánto cuestan.', url: 'https://ingenieriabernal.co/blog/estudio-hidrologico-colombia-que-es' },
  { path: 'blog/proyecto-acueducto-sgr-paso-a-paso', title: 'Cómo formular un proyecto de acueducto rural con recursos SGR en Colombia | BIC', desc: 'Guía paso a paso para formular y presentar un proyecto de acueducto ante el Sistema General de Regalías (SGR) en Colombia. MGA, requisitos, errores comunes.', url: 'https://ingenieriabernal.co/blog/proyecto-acueducto-sgr-paso-a-paso' },
  { path: 'blog/diferencia-bocatoma-captacion-aguas-colombia', title: 'Bocatoma vs captación de aguas en Colombia: diferencias y tipos | BIC', desc: 'Conoce los tipos de bocatomas y sistemas de captación de aguas superficiales en Colombia según el RAS 2017: bocatomas laterales, de fondo, diques, pozos ribereños y más.', url: 'https://ingenieriabernal.co/blog/diferencia-bocatoma-captacion-aguas-colombia' },
  { path: 'blog/cuando-contratar-ingeniero-hidraulico-colombia', title: '¿Cuándo contratar un ingeniero hidráulico en Colombia? 8 situaciones | BIC', desc: 'Descubre cuándo necesitas contratar un ingeniero hidráulico o consultor de ingeniería en Colombia: diseños, trámites ante CARs, proyectos SGR, PTAP, PTAR y más.', url: 'https://ingenieriabernal.co/blog/cuando-contratar-ingeniero-hidraulico-colombia' },
  { path: 'calculadora-estudios-hidraulicos', title: 'Calculadora de Costos — Estudios Hidráulicos | Ingeniería Bernal', desc: 'Estime el costo de su estudio hidrológico, modelación HEC-RAS, diseño de acueducto, PTAR o PTAP en Colombia. Rangos de precio en COP y plazos de entrega. Propuesta técnica formal en 24 horas.', url: 'https://ingenieriabernal.co/calculadora-estudios-hidraulicos' },
  // Batch L — Mayo 2026 (costo HEC-RAS, documentos acueducto veredal)
  { path: 'blog/costo-estudio-hec-ras-colombia-2026', title: '¿Cuánto cuesta un estudio HEC-RAS en Colombia? (2026) | BIC', desc: 'Rangos de precio reales para estudios de inundabilidad con HEC-RAS en Colombia 2026. Qué incluye, qué factores afectan el costo y cómo cotizar correctamente.', url: 'https://ingenieriabernal.co/blog/costo-estudio-hec-ras-colombia-2026' },
  { path: 'blog/documentos-para-contratar-diseno-acueducto-veredal', title: 'Documentos para contratar diseño de acueducto veredal en Colombia | BIC', desc: 'Lista completa de documentos necesarios para contratar un diseño de acueducto veredal en Colombia. Topografía, análisis de agua, censo y más — guía práctica para JAC y alcaldías.', url: 'https://ingenieriabernal.co/blog/documentos-para-contratar-diseno-acueducto-veredal' },
  // Batch M — Mayo 2026 (acueductos rurales y gestión del riesgo hídrico)
  { path: 'blog/caudales-diseno-acueducto-ras-2017', title: 'QMD, QMMD y QMH: cómo calcular los caudales de diseño según RAS 2017 | BIC', desc: 'Guía práctica para calcular QMD, QMMD y QMH en acueductos rurales según el RAS 2017. Fórmulas, factores de mayoración y ejemplos de cálculo para ingenieros y técnicos.', url: 'https://ingenieriabernal.co/blog/caudales-diseno-acueducto-ras-2017' },
  { path: 'blog/materiales-tuberia-acueducto-rural-colombia', title: 'PVC, HDPE o hierro dúctil: qué tubería usar en acueductos rurales en Colombia | BIC', desc: 'Comparación de materiales para redes de acueducto rural en Colombia: PVC, HDPE y hierro dúctil. Cuándo usar cada uno, ventajas, costos y normas aplicables RAS 2017.', url: 'https://ingenieriabernal.co/blog/materiales-tuberia-acueducto-rural-colombia' },
  { path: 'blog/conexiones-domiciliarias-acueducto-veredal', title: 'Conexiones domiciliarias en acueductos veredales: todo lo que debe saber | BIC', desc: 'Guía técnica sobre conexiones domiciliarias en acueductos rurales: componentes, diámetros, materiales, medidores y normativa RAS 2017. Para JAC, plomeros y técnicos.', url: 'https://ingenieriabernal.co/blog/conexiones-domiciliarias-acueducto-veredal' },
  { path: 'blog/irca-calidad-agua-potable-colombia', title: '¿Qué es el IRCA y cómo afecta a su acueducto? Guía práctica 2026 | BIC', desc: 'Guía completa sobre el IRCA (Índice de Riesgo de la Calidad del Agua) en Colombia: qué mide, cómo se calcula, niveles de riesgo y qué debe hacer su acueducto si está en riesgo alto.', url: 'https://ingenieriabernal.co/blog/irca-calidad-agua-potable-colombia' },
  { path: 'blog/mapas-inundacion-colombia-pomca-pot', title: 'Mapas de inundación en Colombia: POMCA, POT y gestión del riesgo | BIC', desc: 'Para qué sirven los mapas de inundación en Colombia, cómo se elaboran con HEC-RAS, y qué relación tienen con el POMCA, el POT y las licencias ambientales.', url: 'https://ingenieriabernal.co/blog/mapas-inundacion-colombia-pomca-pot' },
  // Batch N — Mayo 2026 (interventoría, PTAP veredal, POMCA, edificabilidad, RAS 2017)
  { path: 'blog/interventoria-obras-hidraulicas-colombia', title: 'Interventoría de obras hidráulicas en Colombia: obligaciones, costos y entregables | BIC', desc: 'Guía completa sobre interventoría de obras hidráulicas en Colombia: qué es, obligaciones del interventor según Ley 80/93, diferencia con supervisión, entregables y rangos de costo (3–8% del valor de obra).', url: 'https://ingenieriabernal.co/blog/interventoria-obras-hidraulicas-colombia' },
  { path: 'blog/presupuesto-diseno-ptap-veredal-colombia-2026', title: '¿Cuánto cuesta el diseño de una PTAP veredal en Colombia? (2026) | BIC', desc: 'Rangos de precio reales para diseño de PTAP veredal en Colombia 2026: qué factores determinan el costo, tabla por capacidad (500–2000 personas), qué incluye el diseño completo y fondos disponibles.', url: 'https://ingenieriabernal.co/blog/presupuesto-diseno-ptap-veredal-colombia-2026' },
  { path: 'blog/modelacion-hidraulica-pomca-colombia', title: 'Modelación hidráulica en POMCA: qué exige la normativa y cómo se hace | BIC', desc: 'Qué modelación hidráulica exige un POMCA en Colombia: Decreto 1640/2012, herramientas HEC-HMS y HEC-RAS, mapas de amenaza por inundación (TR 2.33, 10, 100 años) y entregables para las CAR.', url: 'https://ingenieriabernal.co/blog/modelacion-hidraulica-pomca-colombia' },
  { path: 'blog/indice-edificabilidad-colombia-calculo-ejemplo', title: 'Índice de edificabilidad básico en Colombia: definición, fórmula y ejemplo de cálculo | BIC', desc: 'Qué es el índice de edificabilidad básico en Colombia según la Ley 388/1997 y el POT, fórmula de cálculo, diferencia entre IE básico, máximo y en altura, ejemplo para Manizales.', url: 'https://ingenieriabernal.co/blog/indice-edificabilidad-colombia-calculo-ejemplo' },
  { path: 'blog/normas-tecnicas-diseno-acueductos-colombia-ras-2017', title: 'Normas técnicas para diseño de acueductos en Colombia: RAS 2017 y otras referencias | BIC', desc: 'Resumen del RAS 2017 Título B para diseño de acueductos en Colombia: niveles de complejidad, dotaciones, coeficientes de variación, presiones y diferencias con el RAS 2017. Otras normas aplicables.', url: 'https://ingenieriabernal.co/blog/normas-tecnicas-diseno-acueductos-colombia-ras-2017' },
  // Batch A — Hidrología e Hidráulica Técnica
  { path: 'blog/estudio-hidrologico-colombia', title: '¿Qué es un estudio hidrológico y cuándo es obligatorio en Colombia? | BIC', desc: 'Guía técnica completa sobre estudios hidrológicos en Colombia: definición, metodologías, entidades que los exigen y cómo contratar una consultoría especializada. Actualizado 2026.', url: 'https://ingenieriabernal.co/blog/estudio-hidrologico-colombia' },
  { path: 'blog/crecientes-eje-cafetero-colombia', title: 'Hidrología de los ríos del Eje Cafetero: amenazas, caudales y zonificación | BIC', desc: 'Análisis técnico de la hidrología de los principales ríos del Eje Cafetero colombiano: regímenes de caudal, períodos de retorno, eventos históricos y metodologías de análisis vigentes.', url: 'https://ingenieriabernal.co/blog/crecientes-eje-cafetero-colombia' },
  { path: 'blog/analisis-frecuencias-hidrologicas-colombia', title: 'Análisis de frecuencias hidrológicas: metodología y aplicación en proyectos colombianos | BIC', desc: 'Guía técnica sobre análisis de frecuencias para cálculo de caudales de diseño en Colombia: distribuciones estadísticas, períodos de retorno y normativa IDEAM aplicable.', url: 'https://ingenieriabernal.co/blog/analisis-frecuencias-hidrologicas-colombia' },
  { path: 'blog/curvas-idf-colombia', title: 'Curvas IDF en Colombia: metodología, fuentes de datos y uso en diseño de infraestructura | BIC', desc: 'Guía técnica completa sobre curvas Intensidad-Duración-Frecuencia (IDF) en Colombia: metodología IDEAM, estaciones disponibles, ajuste regional y aplicación en diseño de drenajes.', url: 'https://ingenieriabernal.co/blog/curvas-idf-colombia' },
  { path: 'blog/hec-hms-colombia', title: 'HEC-HMS en Colombia: modelación lluvia-escorrentía para estudios hidrológicos | BIC', desc: 'Guía técnica sobre el uso de HEC-HMS en proyectos de hidrología colombiana: configuración de cuencas, métodos de pérdidas, tránsito de crecientes y exportación a HEC-RAS.', url: 'https://ingenieriabernal.co/blog/hec-hms-colombia' },
  { path: 'blog/diseno-canales-colombia', title: 'Diseño hidráulico de canales: fundamentos, fórmulas y normativa colombiana | BIC', desc: 'Manual técnico de diseño hidráulico de canales en Colombia: ecuación de Manning, diseño de canales en tierra y concreto, criterios de velocidad y tirante según RAS 2017.', url: 'https://ingenieriabernal.co/blog/diseno-canales-colombia' },
  { path: 'blog/ronda-hidrica-colombia', title: 'Ronda hídrica en Colombia: qué es, cómo se delimita y qué implica para su municipio | BIC', desc: 'Guía jurídico-técnica sobre ronda hídrica en Colombia: definición según el Decreto 2245 de 2017, metodología de delimitación, obligaciones de alcaldías y ESPs. Con ejemplos prácticos.', url: 'https://ingenieriabernal.co/blog/ronda-hidrica-colombia' },
  { path: 'blog/aforo-caudales-colombia', title: 'Aforo de caudales: métodos, equipos y aplicación en proyectos hidráulicos colombianos | BIC', desc: 'Guía técnica sobre aforo de caudales en Colombia: método del flotador, molinete, ADCP, dilución de trazadores. Cuándo usar cada método y cómo interpretar los datos.', url: 'https://ingenieriabernal.co/blog/aforo-caudales-colombia' },
  { path: 'blog/modelacion-1d-2d-colombia', title: 'Modelación hidráulica 1D vs 2D en Colombia: guía técnica para tomar la decisión correcta | BIC', desc: 'Comparación técnica entre modelación hidráulica 1D (HEC-RAS, ISIS) y 2D (HEC-RAS 2D, MIKE FLOOD) para proyectos colombianos: criterios de selección, costos y resultados.', url: 'https://ingenieriabernal.co/blog/modelacion-1d-2d-colombia' },
];

// Páginas con noindex (thin content — duplican contenido de páginas de mayor valor)
const NOINDEX_PATHS = new Set([
  'ingenieria-bogota', 'ingenieria-medellin', 'ingenieria-cali',
  'ingenieria-manizales', 'ingenieria-bucaramanga', 'ingenieria-barranquilla',
  'ingenieria-eje-cafetero', 'ingenieria-antioquia',
]);

// Páginas redirigidas (canonical apunta a la URL definitiva)
const REDIRECT_PAGES = {
  'servicios/acueducto-alcantarillado': 'https://ingenieriabernal.co/servicios/diseno-acueductos',
};

function injectMeta(html, r) {
  let result = html
    .replace(/<title>[^<]*<\/title>/, `<title>${r.title}</title>`)
    .replace(/<meta name="description" content="[^"]*"/, `<meta name="description" content="${r.desc}"`)
    .replace(/<link rel="canonical" href="[^"]*"/, `<link rel="canonical" href="${r.url}"`)
    .replace(/<meta property="og:url" content="[^"]*"/, `<meta property="og:url" content="${r.url}"`)
    .replace(/<meta property="og:title" content="[^"]*"/, `<meta property="og:title" content="${r.title}"`)
    .replace(/<meta property="og:description" content="[^"]*"/, `<meta property="og:description" content="${r.desc}"`)
    .replace(/<meta name="twitter:title" content="[^"]*"/, `<meta name="twitter:title" content="${r.title}"`)
    .replace(/<meta name="twitter:description" content="[^"]*"/, `<meta name="twitter:description" content="${r.desc}"`);

  // Noindex para páginas de thin content
  if (NOINDEX_PATHS.has(r.path)) {
    result = result.replace(/<meta name="robots" content="[^"]*"/, '<meta name="robots" content="noindex, follow"');
  }

  return result;
}

// Redireccionamientos: crear HTML con meta refresh + canonical a la URL definitiva
for (const [fromPath, toUrl] of Object.entries(REDIRECT_PAGES)) {
  const dir = join(distDir, fromPath);
  mkdirSync(dir, { recursive: true });
  const redirectHtml = baseHtml
    .replace(/<title>[^<]*<\/title>/, `<title>Redirigiendo…</title>`)
    .replace(/<meta name="robots" content="[^"]*"/, '<meta name="robots" content="noindex, follow"')
    .replace(/<link rel="canonical" href="[^"]*"/, `<link rel="canonical" href="${toUrl}"`)
    .replace('</head>', `  <meta http-equiv="refresh" content="0;url=${toUrl}">\n</head>`);
  writeFileSync(join(dir, 'index.html'), redirectHtml, 'utf-8');
  console.log(`  ↪️  /${fromPath} → ${toUrl}`);
}

for (const route of routes) {
  const html = injectMeta(baseHtml, route);
  const dir = join(distDir, route.path);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.html'), html, 'utf-8');
  const marker = NOINDEX_PATHS.has(route.path) ? '🚫' : '✅';
  console.log(`  ${marker} /${route.path}`);
}

console.log(`\n✅ Pre-rendering completo: ${routes.length} rutas generadas.`);
