import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, 'dist');
const indexPath = join(distDir, 'index.html');

if (!existsSync(indexPath)) {
  console.error('ERROR: dist/index.html no encontrado. Ejecuta vite build primero.');
  process.exit(1);
}

const baseHtml = readFileSync(indexPath, 'utf-8');

const routes = [
  // Páginas principales
  { path: 'servicios', title: 'Servicios de Ingeniería Hidráulica — BIC Bernal Ingeniería | Manizales', desc: 'Hidrosanitario, CI NSR-10, HEC-RAS 2D, acueducto, alcantarillado, gestión del riesgo, regalías MGA-Web. BIC — Manizales, Eje Cafetero, Colombia.', url: 'https://ingenieriabernal.co/servicios' },
  { path: 'proyectos', title: 'Proyectos Ejecutados — BIC Bernal Ingeniería | Caldas y Colombia', desc: 'Portafolio verificado: Palacio de Justicia La Dorada, Makarí Mall Dosquebradas, EPANET Manizales, torrencialidad Eje Cafetero. BIC — más de 10 años de experiencia.', url: 'https://ingenieriabernal.co/proyectos' },
  { path: 'equipo', title: 'Equipo Consultor — BIC Bernal Ingeniería Consultores | Manizales', desc: 'Rogerio Bernal Ríos, Ing. Civil Esp. Hidráulica UNAL, COPNIA 17202-313228. Equipo multidisciplinario: hidráulica, geotecnia, arquitectura, ambiental.', url: 'https://ingenieriabernal.co/equipo' },
  { path: 'blog', title: 'Blog Ingeniería Hidráulica Colombia — Artículos Técnicos BIC', desc: 'Artículos técnicos: HEC-RAS 2D, NSR-10 sistemas CI, costos obras 2026, regalías MGA-Web, normativa hídrica colombiana. Por Rogerio Bernal Ríos.', url: 'https://ingenieriabernal.co/blog' },
  { path: 'contacto', title: 'Contacto — BIC Bernal Ingeniería Consultores | Manizales, Colombia', desc: 'Contáctenos para proyectos de ingeniería hidráulica, hidrosanitaria y gestión del riesgo. Manizales, Eje Cafetero, Colombia.', url: 'https://ingenieriabernal.co/contacto' },
  { path: 'sobre-mi', title: 'Sobre Mí — Rogerio Bernal Ríos | BIC Bernal Ingeniería Consultores', desc: 'Rogerio Bernal Ríos, Ingeniero Civil UNAL Manizales, Especialista en Hidráulica. Director de BIC Bernal Ingeniería Consultores. COPNIA 17202-313228. Más de 10 años de experiencia.', url: 'https://ingenieriabernal.co/sobre-mi' },
  { path: 'credenciales', title: 'Credenciales y Certificaciones | BIC Bernal Ingeniería Consultores', desc: 'Credenciales de Rogerio Bernal Ríos: Ing. Civil UNAL, Especialista Hidráulica, COPNIA 17202-313228, TOEFL 98/120. Experiencia internacional en Ecuador y México.', url: 'https://ingenieriabernal.co/credenciales' },
  { path: 'cobertura-nacional', title: 'Cobertura Nacional — Ingeniería Hidráulica Colombia | BIC', desc: 'BIC Bernal Ingeniería Consultores presta servicios en todo Colombia: Eje Cafetero, Bogotá, Medellín, Cali, Barranquilla, Bucaramanga y regiones del Pacífico, Caribe y Llanos.', url: 'https://ingenieriabernal.co/cobertura-nacional' },

  // Landing pages ciudades / regiones
  { path: 'ingenieria-hidraulica-manizales', title: 'Ingeniería Hidráulica Manizales — BIC Bernal Ingeniería Consultores', desc: 'Consultoría hidráulica, hidrosanitaria y gestión del riesgo en Manizales y Caldas. EPANET, HEC-RAS 2D, NSR-10. Más de 10 años de experiencia local.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-manizales' },
  { path: 'ingenieria-hidraulica-eje-cafetero', title: 'Ingeniería Hidráulica Eje Cafetero — BIC Bernal Ingeniería', desc: 'Proyectos hidráulicos en Manizales, Pereira, Armenia y toda la región cafetera. Modelación HEC-RAS, torrencialidad, acueductos rurales.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-eje-cafetero' },
  { path: 'ingenieria-hidraulica-bogota', title: 'Ingeniería Hidráulica Bogotá — BIC Bernal Ingeniería Consultores', desc: 'Consultoría hidráulica y estructural para proyectos en Bogotá D.C. Diseño hidrosanitario NSR-10, memorias de cálculo, revisión de proyectos.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-bogota' },
  { path: 'ingenieria-hidraulica-medellin', title: 'Ingeniería Hidráulica Medellín — BIC Bernal Ingeniería Consultores', desc: 'Servicios de ingeniería hidráulica e hidrosanitaria en Medellín y Área Metropolitana. Antioquia. Diseño, modelación y consultoría técnica.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-medellin' },
  { path: 'ingenieria-hidraulica-pereira', title: 'Ingeniería Hidráulica Pereira — BIC Bernal Ingeniería Consultores', desc: 'Consultoría hidráulica en Pereira y Risaralda. Modelación HEC-RAS, estudios hidrológicos, diseño hidrosanitario NSR-10.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-pereira' },
  { path: 'ingenieria-hidraulica-armenia', title: 'Ingeniería Hidráulica Armenia — BIC Bernal Ingeniería Consultores', desc: 'Proyectos de ingeniería hidráulica en Armenia y Quindío. Estudios de inundación, modelación hidráulica y diseño hidrosanitario.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-armenia' },
  { path: 'ingenieria-hidraulica-cali', title: 'Ingeniería Hidráulica Cali — BIC Bernal Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica para proyectos en Cali y Valle del Cauca. Modelación hidrodinámica, gestión del riesgo hídrico.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-cali' },
  { path: 'ingenieria-hidraulica-colombia', title: 'Ingeniería Hidráulica Colombia — BIC Bernal Ingeniería Consultores', desc: 'Consultoría nacional en ingeniería hidráulica: acueductos, alcantarillados, inundaciones, torrencialidad y regalías MGA-Web. BIC — Colombia.', url: 'https://ingenieriabernal.co/ingenieria-hidraulica-colombia' },

  // Servicios específicos
  { path: 'hec-ras-modelacion-hidraulica', title: 'Modelación HEC-RAS 2D Colombia — BIC Bernal Ingeniería Consultores', desc: 'Modelación hidráulica con HEC-RAS 2D para estudios de inundación, torrencialidad y planes de ordenamiento. Expertos certificados en Colombia.', url: 'https://ingenieriabernal.co/hec-ras-modelacion-hidraulica' },
  { path: 'diseno-hidrosanitario-nsr10', title: 'Diseño Hidrosanitario NSR-10 — BIC Bernal Ingeniería | Colombia', desc: 'Diseño de sistemas CI (contraincendio), hidrosanitarios y memorias de cálculo bajo NSR-10 Título I. Edificios, hospitales, centros comerciales.', url: 'https://ingenieriabernal.co/diseno-hidrosanitario-nsr10' },
  { path: 'estudios-inundacion-colombia', title: 'Estudios de Inundación Colombia — BIC Bernal Ingeniería Consultores', desc: 'Estudios de amenaza y riesgo de inundación para POT, licencias ambientales y seguros. Metodología IDEAM, modelación 2D. Cobertura nacional.', url: 'https://ingenieriabernal.co/estudios-inundacion-colombia' },
  { path: 'acueductos-alcantarillados', title: 'Diseño Acueductos y Alcantarillados — BIC Bernal Ingeniería Colombia', desc: 'Diseño y optimización de sistemas de acueducto y alcantarillado bajo RAS 2000. Modelos EPANET, WaterGEMS. Zonas urbanas y rurales de Colombia.', url: 'https://ingenieriabernal.co/acueductos-alcantarillados' },
  { path: 'regalias-mga-web', title: 'Proyectos Regalías MGA-Web — BIC Bernal Ingeniería | Colombia', desc: 'Formulación y estructuración de proyectos de inversión MGA-Web para el Sistema General de Regalías (SGR). Alcaldías, gobernaciones, entidades públicas.', url: 'https://ingenieriabernal.co/regalias-mga-web' },
  { path: 'gestion-riesgo-hidrico', title: 'Gestión del Riesgo Hídrico Colombia — BIC Bernal Ingeniería', desc: 'Planes municipales de gestión del riesgo hídrico, mapas de amenaza, PMGRD. Integración con POT y POMCA. Experiencia Eje Cafetero y Colombia.', url: 'https://ingenieriabernal.co/gestion-riesgo-hidrico' },

  // Servicios específicos (sub-páginas)
  { path: 'servicios/estudio-inundabilidad-manizales', title: 'Estudio de Inundabilidad Manizales | BIC Bernal Ingeniería Consultores', desc: 'Estudio de inundabilidad en Manizales con modelación HEC-RAS 2D. Requerido por Corpocaldas, POT y POMCA Río Chinchiná. Manchas de inundación, amenaza hídrica Decreto 1807/2014. BIC — Manizales.', url: 'https://ingenieriabernal.co/servicios/estudio-inundabilidad-manizales' },
  { path: 'servicios/estudios-hidrologicos', title: 'Estudios Hidrológicos Colombia | BIC Bernal Ingeniería Consultores', desc: 'Estudios hidrológicos para municipios, constructoras y entidades públicas en Colombia. Análisis de cuencas, curvas IDF, caudales de diseño, periodos de retorno. Director PhD. +30 años experiencia. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/estudios-hidrologicos' },
  { path: 'servicios/modelacion-hec-ras', title: 'Modelación Hidráulica HEC-RAS 2D Colombia | BIC Bernal Ingeniería Consultores', desc: 'Modelación hidráulica HEC-RAS 1D y 2D para municipios, constructoras y entidades en Colombia. Manchas de inundación, amenaza hídrica Decreto 1807/2014. Director PhD. +30 años. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/modelacion-hec-ras' },
  { path: 'servicios/acueducto-alcantarillado', title: 'Diseño Acueducto y Alcantarillado Colombia | BIC Bernal Ingeniería Consultores', desc: 'Diseño de acueductos y alcantarillados para municipios y constructoras en Colombia. RAS 2017, Resolución 0330/2017. Redes de distribución, colectores, PTAP, PTAR. Director PhD. +30 años.', url: 'https://ingenieriabernal.co/servicios/acueducto-alcantarillado' },
  { path: 'servicios/redes-hidrosanitarias', title: 'Redes Hidrosanitarias para Edificaciones | BIC Bernal Ingeniería Consultores', desc: 'Diseño de redes hidrosanitarias para edificios residenciales, comerciales e industriales en Colombia. Agua fría, agua caliente, aguas residuales, aguas lluvias. NSR-10, RAS 2017. Director PhD.', url: 'https://ingenieriabernal.co/servicios/redes-hidrosanitarias' },
  { path: 'servicios/sistemas-contra-incendio', title: 'Sistemas Contra Incendio NSR-10 Colombia | BIC Bernal Ingeniería Consultores', desc: 'Diseño de sistemas contra incendio NSR-10 Títulos J y K para edificios, centros comerciales, plantas industriales y bodegas en Colombia. NFPA, rociadores, hidrantes. Director PhD. +30 años.', url: 'https://ingenieriabernal.co/servicios/sistemas-contra-incendio' },
  { path: 'servicios/interventoria', title: 'Interventoría Técnica Hidráulica Colombia | BIC Bernal Ingeniería Consultores', desc: 'Interventoría técnica de obras hidráulicas, acueductos, alcantarillados y redes hidrosanitarias para municipios, gobernaciones y entidades públicas en Colombia. Director PhD. +30 años.', url: 'https://ingenieriabernal.co/servicios/interventoria' },
  { path: 'servicios/regalias-mga', title: 'Formulación Proyectos Regalías MGA-Web Colombia | BIC Bernal Ingeniería Consultores', desc: 'Formulación de proyectos de inversión para el Sistema General de Regalías (SGR) en MGA-Web. Agua potable, saneamiento básico, gestión del riesgo. Director PhD. +30 años. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/regalias-mga' },
  { path: 'servicios/geotecnia', title: 'Estudios Geotécnicos y de Suelos Colombia | BIC Bernal Ingeniería Consultores', desc: 'Estudios geotécnicos y de suelos para constructoras, municipios y entidades públicas en Colombia. Capacidad portante, estabilidad de taludes, NSR-10 Título H. Director PhD. +30 años.', url: 'https://ingenieriabernal.co/servicios/geotecnia' },
  { path: 'servicios/ambiental', title: 'Estudios Ambientales e IRCA Colombia | BIC Bernal Ingeniería Consultores', desc: 'Estudios ambientales, cálculo IRCA, permisos de vertimientos, concesiones de agua y trámites ante CAR para proyectos hídricos en Colombia. Director PhD. +30 años. Eje Cafetero.', url: 'https://ingenieriabernal.co/servicios/ambiental' },

  // Páginas regionales SEO
  { path: 'regional/manizales', title: 'Ingeniería Hidráulica Manizales | BIC Bernal Ingeniería Consultores', desc: 'BIC tiene su sede en Manizales. Estudios hidrológicos, diseño de acueductos, alcantarillados y modelación HEC-RAS para alcaldías, constructoras y ESP en Caldas y Eje Cafetero.', url: 'https://ingenieriabernal.co/regional/manizales' },
  { path: 'regional/pereira', title: 'Ingeniería Hidráulica Pereira | BIC Bernal Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica y sanitaria en Pereira y Risaralda. Diseño de acueductos, redes contra incendio y modelaciones HEC-RAS para sector público y privado.', url: 'https://ingenieriabernal.co/regional/pereira' },
  { path: 'regional/armenia', title: 'Ingeniería Hidráulica Armenia | BIC Bernal Ingeniería Consultores', desc: 'Consultoría hidráulica en Armenia y Quindío. Estudios hidráulicos, formulación de proyectos de regalías (MGA-Web) y diseño de redes hidrosanitarias con cumplimiento RAS 2000.', url: 'https://ingenieriabernal.co/regional/armenia' },
  { path: 'regional/eje-cafetero', title: 'Consultoría Hidráulica Eje Cafetero | BIC Bernal Ingeniería Consultores', desc: 'BIC opera en todo el Eje Cafetero — Caldas, Risaralda y Quindío. Consultoría integral en ingeniería hidráulica, sanitaria y ambiental para infraestructura pública y privada.', url: 'https://ingenieriabernal.co/regional/eje-cafetero' },

  // Landing pages locales — Manizales
  { path: 'estudio-de-inundabilidad-manizales', title: 'Estudio de Inundabilidad en Manizales | BIC Ingeniería', desc: 'Estudios de inundabilidad en Manizales con modelación HEC-RAS 2D. Requerido por Corpocaldas, POMCA y POT. Solicite cotización: +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-inundabilidad-manizales/' },
  { path: 'estudio-de-suelos-manizales', title: 'Estudio de Suelos en Manizales | BIC Ingeniería', desc: 'Realizamos estudios de suelos en Manizales según NSR-10. Informe geotécnico completo para licencia de construcción. Solicite cotización: +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-manizales/' },
  { path: 'licencia-de-construccion-manizales', title: 'Licencia de Construcción Manizales: Documentos Técnicos | BIC', desc: 'BIC prepara todos los estudios técnicos para su licencia de construcción en Manizales: suelos, estructural y planos. +57 302 477 8910', url: 'https://ingenieriabernal.co/licencia-de-construccion-manizales/' },
  { path: 'estudio-de-suelos-pereira', title: 'Estudio de Suelos en Pereira | BIC Ingeniería', desc: 'Realizamos estudios de suelos en Pereira según NSR-10. Informe geotécnico completo para licencia de construcción en Risaralda. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-pereira/' },
  { path: 'diseno-hidraulico-manizales', title: 'Diseño Hidráulico en Manizales | BIC Ingeniería', desc: 'Diseño hidráulico en Manizales: redes de acueducto, alcantarillado, canales y estructuras. BIC cumple RAS 2000 y normativa vigente. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-manizales/' },
  { path: 'modelacion-hidraulica-manizales', title: 'Modelación Hidráulica en Manizales | BIC Ingeniería', desc: 'Modelación hidráulica 1D y 2D en Manizales con HEC-RAS. Análisis de inundaciones, socavación y diseño de obras. +57 302 477 8910', url: 'https://ingenieriabernal.co/modelacion-hidraulica-manizales/' },
  { path: 'estudio-hidrologico-manizales', title: 'Estudio Hidrológico en Manizales | BIC Ingeniería', desc: 'Estudios hidrológicos en Manizales: caudales de diseño, curvas IDF, períodos de retorno. Cumplimiento RAS 2000 y EIA. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-hidrologico-manizales/' },
  { path: 'interventoria-hidraulica-manizales', title: 'Interventoría Hidráulica en Manizales | BIC Ingeniería', desc: 'Interventoría técnica de obras hidráulicas en Manizales y Caldas. Acueductos, alcantarillados, canales. RAS 2000. +57 302 477 8910', url: 'https://ingenieriabernal.co/interventoria-hidraulica-manizales/' },
  { path: 'diseno-hidraulico-pereira', title: 'Diseño Hidráulico en Pereira | BIC Ingeniería', desc: 'Diseño hidráulico en Pereira: redes de acueducto, alcantarillado, canales. Cumplimos RAS 2000 y normativa CARDER. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-pereira/' },
  { path: 'estudio-de-inundabilidad-pereira', title: 'Estudio de Inundabilidad en Pereira | BIC Ingeniería', desc: 'Estudios de inundabilidad en Pereira con HEC-RAS 2D. Requerido por CARDER, POT Pereira y licencias de construcción. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-inundabilidad-pereira/' },
  { path: 'licencia-de-construccion-pereira', title: 'Licencia de Construcción Pereira: Documentos Técnicos | BIC', desc: 'BIC prepara estudios técnicos para licencia de construcción en Pereira: suelos, estructural, planos. Curadurías de Pereira. +57 302 477 8910', url: 'https://ingenieriabernal.co/licencia-de-construccion-pereira/' },
  { path: 'estudio-de-suelos-eje-cafetero', title: 'Estudio de Suelos Eje Cafetero | BIC Ingeniería', desc: 'Estudios de suelos en el Eje Cafetero: Manizales, Pereira y Armenia. Suelos volcánicos y cenizas del Quindío. NSR-10. +57 302 477 8910', url: 'https://ingenieriabernal.co/estudio-de-suelos-eje-cafetero/' },
  { path: 'consultoria-ingenieria-civil-manizales', title: 'Consultoría Ingeniería Civil Manizales | BIC', desc: 'Consultoría integral de ingeniería civil en Manizales: estudios técnicos, diseño, interventoría y gestión de proyectos. +57 302 477 8910', url: 'https://ingenieriabernal.co/consultoria-ingenieria-civil-manizales/' },
  { path: 'gestion-riesgo-hidrico-manizales', title: 'Gestión del Riesgo Hídrico Manizales | BIC Ingeniería', desc: 'Gestión del riesgo por inundaciones y avenidas torrenciales en Manizales y Caldas. Planes de contingencia y mitigación. +57 302 477 8910', url: 'https://ingenieriabernal.co/gestion-riesgo-hidrico-manizales/' },
  { path: 'diseno-hidraulico-eje-cafetero', title: 'Diseño Hidráulico Eje Cafetero | BIC Ingeniería', desc: 'Diseño hidráulico en Caldas, Risaralda y Quindío. Redes de acueducto, alcantarillado y estructuras. BIC cubre todo el Eje Cafetero. +57 302 477 8910', url: 'https://ingenieriabernal.co/diseno-hidraulico-eje-cafetero/' },
  { path: 'topografia-manizales', title: 'Topografía en Manizales | BIC Ingeniería', desc: 'Levantamientos topográficos en Manizales para diseño hidráulico, licencias de construcción y estudios de suelos. +57 302 477 8910', url: 'https://ingenieriabernal.co/topografia-manizales/' },

  // Páginas de ciudad — CityPage
  { path: 'manizales', title: 'Ingeniería Hidráulica Manizales — BIC Bernal Ingeniería | Ciudad Base', desc: 'Ciudad base de BIC. Proyectos activos en drenaje urbano, hidrosanitarios, sistemas CI y gestión del riesgo para planes parciales y POT en Manizales, Caldas.', url: 'https://ingenieriabernal.co/manizales' },
  { path: 'eje-cafetero', title: 'Ingeniería Hidráulica Eje Cafetero — BIC Bernal Ingeniería', desc: 'BIC ejecutó diseño hidrosanitario y CI del Makarí Mall en Dosquebradas. Estudios riesgo hídrico, sistemas CI NSR-10, acueducto y alcantarillado en Pereira, Armenia y Dosquebradas.', url: 'https://ingenieriabernal.co/eje-cafetero' },
  { path: 'palestina-aerocafe', title: 'Ingeniería Hidráulica Palestina — Aerocafé | BIC Bernal', desc: 'Sede del Aeropuerto Internacional del Café. Drenaje pluvial aeroportuario, estudios riesgo hídrico Decreto 1807, diseño hidrosanitario industrial. Inversión activa $828.000 millones, Palestina Caldas.', url: 'https://ingenieriabernal.co/palestina-aerocafe' },
  { path: 'viterbo-occidente-caldas', title: 'Ingeniería Hidráulica Viterbo y Occidente de Caldas — BIC', desc: 'Zona de clientela directa de BIC. EOT componente hídrico, acueducto y alcantarillado municipal, proyectos regalías. Anserma, Belalcázar, San José, Risaralda municipio, Caldas.', url: 'https://ingenieriabernal.co/viterbo-occidente-caldas' },
  { path: 'alto-occidente-caldas', title: 'Ingeniería Hidráulica Alto Occidente de Caldas — BIC', desc: 'Corredor minero Riosucio, Supía, Marmato, Filadelfia, La Merced. Centro Desarrollo Minero Marmato $21.000 millones. Estudios geotécnicos, hidráulicos y riesgo. Formulación regalías SGR.', url: 'https://ingenieriabernal.co/alto-occidente-caldas' },
  { path: 'magdalena-medio', title: 'Ingeniería Hidráulica Magdalena Medio — BIC Bernal', desc: 'La Dorada, Honda, Puerto Boyacá, Barrancabermeja. BIC ejecutó Palacio de Justicia La Dorada. Estudios inundación río Magdalena, sistemas CI, formulación proyectos regalías MGA-Web.', url: 'https://ingenieriabernal.co/magdalena-medio' },
  { path: 'norte-tolima', title: 'Ingeniería Hidráulica Norte del Tolima — BIC Bernal', desc: 'Líbano, Fresno, Mariquita, Herveo, Honda. Zona sin competencia SEO. Acueducto y alcantarillado rural, estudios riesgo hídrico, gestión POT. BIC Bernal Ingeniería.', url: 'https://ingenieriabernal.co/norte-tolima' },
  { path: 'cerritos-norte-valle', title: 'Ingeniería Hidráulica Cerritos y Norte del Valle — BIC', desc: '22 planes parciales activos en Cerritos y Norte del Valle. Estudios riesgo hídrico obligatorio Decreto 1807/2014. Drenaje pluvial industrial, sistemas CI NSR-10. Cartago, Valle del Cauca.', url: 'https://ingenieriabernal.co/cerritos-norte-valle' },
  { path: 'rionegro-oriente-antioquia', title: 'Ingeniería Hidráulica Rionegro y Oriente Antioquia — BIC', desc: 'Parques industriales, centros logísticos, urbanizaciones en expansión. Corredor Aeropuerto José María Córdova. Estudios riesgo hídrico, diseño hidrosanitario, sistemas CI. BIC Bernal.', url: 'https://ingenieriabernal.co/rionegro-oriente-antioquia' },
  { path: 'sabana-occidente', title: 'Ingeniería Hidráulica Sabana Occidente — BIC Bernal', desc: 'Mosquera, Facatativá, Madrid, Funza, Bojacá. Corredor industrial Cundinamarca. Zonas francas, bodegas logísticas, sistemas CI NSR-10, permisos CAR Cundinamarca.', url: 'https://ingenieriabernal.co/sabana-occidente' },
  { path: 'sabana-norte', title: 'Ingeniería Hidráulica Sabana Norte — BIC Bernal', desc: 'Tocancipá, Zipaquirá, Cajicá, Chía, Sopó. Mayor crecimiento industrial norte de Bogotá. Estudios riesgo hídrico planes parciales, sistemas CI NSR-10, formulación regalías SGR.', url: 'https://ingenieriabernal.co/sabana-norte' },
  { path: 'boyaca-corredor', title: 'Ingeniería Hidráulica Corredor Boyacá — BIC Bernal', desc: 'Duitama, Sogamoso, Paipa, Nobsa, Tibasosa. Corredor acerero y turístico. Diseño hidrosanitario industrial, sistemas CI plantas industriales, acueducto y alcantarillado.', url: 'https://ingenieriabernal.co/boyaca-corredor' },
  { path: 'huila-neiva', title: 'Ingeniería Hidráulica Huila — BIC Bernal Ingeniería', desc: 'Neiva, Pitalito, Campoalegre, Garzón. Regalías petroleras e hidroeléctricas. Diseño acueducto y alcantarillado, estudios inundación río Magdalena, formulación proyectos MGA-Web.', url: 'https://ingenieriabernal.co/huila-neiva' },
  { path: 'bucaramanga-area', title: 'Ingeniería Hidráulica Área Metropolitana Bucaramanga — BIC', desc: 'Floridablanca, Girón, Piedecuesta, Barrancabermeja. DNP: Floridablanca mejor evaluada de Colombia. Diseño hidrosanitario, sistemas CI NSR-10, estudios riesgo hídrico, CDMB.', url: 'https://ingenieriabernal.co/bucaramanga-area' },
  { path: 'santander-sur', title: 'Ingeniería Hidráulica Santander Sur — BIC Bernal', desc: 'Barbosa, Socorro, San Gil, Barichara, Charalá. Turismo activo, agroindustria. Estudios riesgo hídrico, diseño acueducto rural, formulación proyectos regalías SGR.', url: 'https://ingenieriabernal.co/santander-sur' },
  { path: 'antioquia-suroeste', title: 'Ingeniería Hidráulica Suroeste Antioqueño — BIC Bernal', desc: 'Andes, La Pintada, Jardín, Jericó, Valparaíso. Autopistas 4G Pacífico 1 y 2. Estudios riesgo hídrico infraestructura vial, acueducto, gestión torrencialidad. BIC Bernal.', url: 'https://ingenieriabernal.co/antioquia-suroeste' },
  { path: 'costa-caribe', title: 'Ingeniería Hidráulica Costa Caribe — BIC Bernal', desc: 'Montería, Sincelejo, Valledupar, Riohacha. Expansión urbana activa en capitales intermedias. Diseño acueducto, formulación proyectos regalías MGA-Web, gestión riesgo hídrico costero.', url: 'https://ingenieriabernal.co/costa-caribe' },
  { path: 'llanos-orinoquia', title: 'Ingeniería Hidráulica Llanos y Orinoquía — BIC Bernal', desc: 'Villavicencio, Yopal, Acacías, Granada, Aguazul. Regalías petroleras y gasíferas. Formulación proyectos MGA-Web, diseño acueducto rural, estudios inundación llanura aluvial.', url: 'https://ingenieriabernal.co/llanos-orinoquia' },

  // Páginas ingeniería por ciudad (RegionalPage)
  { path: 'ingenieria-bogota', title: 'Ingeniería Hidráulica Bogotá | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores ofrece consultoría en ingeniería hidráulica en Bogotá y Cundinamarca: diseño hidráulico, estudios hidrológicos HEC-RAS, acueductos, geotecnia y PSMV. COPNIA 17202-313228.', url: 'https://ingenieriabernal.co/ingenieria-bogota' },
  { path: 'ingenieria-medellin', title: 'Ingeniería Hidráulica Medellín | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Medellín y Antioquia. BIC ofrece diseño hidráulico, modelación HEC-RAS, acueductos y alcantarillado, geotecnia y PSMV. Equipo multidisciplinario · UNAL · COPNIA.', url: 'https://ingenieriabernal.co/ingenieria-medellin' },
  { path: 'ingenieria-cali', title: 'Ingeniería Hidráulica Cali | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en Cali y Valle del Cauca: ingeniería hidráulica, estudios hidrológicos, diseño de acueductos y alcantarillado, geotecnia y PSMV. 10+ años de experiencia en Colombia.', url: 'https://ingenieriabernal.co/ingenieria-cali' },
  { path: 'ingenieria-manizales', title: 'Ingeniería Hidráulica Manizales | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores, con sede en Manizales, Caldas: consultoría en ingeniería hidráulica, diseño hidrosanitario NSR-10, modelación HEC-RAS, acueductos Res. 0330/2017, geotecnia y PSMV.', url: 'https://ingenieriabernal.co/ingenieria-manizales' },
  { path: 'ingenieria-bucaramanga', title: 'Ingeniería Hidráulica Bucaramanga | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Bucaramanga y Santander. BIC ofrece diseño hidráulico, estudios hidrológicos HEC-RAS, acueductos, alcantarillado, geotecnia y PSMV. COPNIA · UNAL.', url: 'https://ingenieriabernal.co/ingenieria-bucaramanga' },
  { path: 'ingenieria-barranquilla', title: 'Ingeniería Hidráulica Barranquilla | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en Barranquilla y el Atlántico: ingeniería hidráulica, estudios de inundación, acueductos y alcantarillado, geotecnia, PSMV y gestión del riesgo hídrico costero.', url: 'https://ingenieriabernal.co/ingenieria-barranquilla' },
  { path: 'ingenieria-eje-cafetero', title: 'Ingeniería Hidráulica Eje Cafetero | BIC Ingeniería Consultores', desc: 'BIC Bernal Ingeniería Consultores en el Eje Cafetero (Pereira, Armenia, Dosquebradas): consultoría hidráulica, diseño hidrosanitario NSR-10, estudios Decreto 1807, acueductos, geotecnia y PSMV.', url: 'https://ingenieriabernal.co/ingenieria-eje-cafetero' },
  { path: 'ingenieria-antioquia', title: 'Ingeniería Hidráulica Antioquia | BIC Ingeniería Consultores', desc: 'Consultoría en ingeniería hidráulica en Antioquia. BIC ofrece diseño hidráulico, modelación HEC-RAS, estudios hidrológicos, acueductos Res. 0330/2017, geotecnia, PSMV y gestión del riesgo hídrico.', url: 'https://ingenieriabernal.co/ingenieria-antioquia' },

  // Blog posts
  { path: 'blog/irca-municipio-colombia', title: 'Cómo bajar el IRCA de un municipio en Colombia | BIC Bernal Ingeniería', desc: 'Aprenda qué es el IRCA, por qué sube, cuáles son las causas más comunes en municipios colombianos y qué pasos concretos puede tomar para reducirlo. Información técnica con respaldo normativo.', url: 'https://ingenieriabernal.co/blog/irca-municipio-colombia' },
  { path: 'blog/mga-web-regalias-agua-potable', title: 'Formulación proyectos agua potable con regalías y MGA Web Colombia | BIC', desc: 'Guía práctica para alcaldes, secretarios de planeación y gestores del SGR sobre cómo formular proyectos de acueducto en la MGA Web sin cometer los errores que hacen devolver los proyectos.', url: 'https://ingenieriabernal.co/blog/mga-web-regalias-agua-potable' },
  { path: 'blog/hec-ras-2d-modelacion-hidraulica-colombia', title: 'Contratar modelación hidráulica HEC-RAS 2D en Colombia | BIC Bernal Ingeniería', desc: 'Guía técnica para constructoras, promotores e ingenieros sobre qué es la modelación HEC-RAS 2D, cuándo es obligatoria en Colombia y qué debe incluir un modelo bien hecho.', url: 'https://ingenieriabernal.co/blog/hec-ras-2d-modelacion-hidraulica-colombia' },
];

function injectMeta(html, r) {
  return html
    .replace(/<title>[^<]*<\/title>/, `<title>${r.title}</title>`)
    .replace(/<meta name="description" content="[^"]*"/, `<meta name="description" content="${r.desc}"`)
    .replace(/<link rel="canonical" href="[^"]*"/, `<link rel="canonical" href="${r.url}"`)
    .replace(/<meta property="og:url" content="[^"]*"/, `<meta property="og:url" content="${r.url}"`)
    .replace(/<meta property="og:title" content="[^"]*"/, `<meta property="og:title" content="${r.title}"`)
    .replace(/<meta property="og:description" content="[^"]*"/, `<meta property="og:description" content="${r.desc}"`)
    .replace(/<meta name="twitter:title" content="[^"]*"/, `<meta name="twitter:title" content="${r.title}"`)
    .replace(/<meta name="twitter:description" content="[^"]*"/, `<meta name="twitter:description" content="${r.desc}"`);
}

for (const route of routes) {
  const html = injectMeta(baseHtml, route);
  const dir = join(distDir, route.path);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.html'), html, 'utf-8');
  console.log(`  ✅ /${route.path}`);
}

console.log(`\n✅ Pre-rendering completo: ${routes.length} rutas generadas.`);
